/* ===== VERBS, part A — lessons V1–V14 ===== */
const VERBS_A = [
{t:"Being, wanting, needing", c:"Verbs · The engine room", w:[
 {en:"To be", inf:"Li-hiot", infHe:"לִהְיוֹת", tr:"— (no present tense)", he:"—",
  mn:"Hebrew simply DROPS 'am/is/are'. \"I am tired\" = Ani ayef — literally \"I tired.\" Think of li-HIOT as a verb that takes a HIatus in the present.",
  ex:["Ani rotza lihiot rofa.","אֲנִי רוֹצָה לִהְיוֹת רוֹפְאָה.","I want to be a doctor."]},
 {en:"To be able to / can", inf:"Li-hiot mesugal", infHe:"לִהְיוֹת מְסֻגָּל", tr:"Yachol / Yechola", he:"יָכוֹל / יְכוֹלָה",
  mn:"ya-CHOL = \"Ya, cool!\" — Yes, I can, no problem.",
  ex:["Ani lo yechola lavo machar.","אֲנִי לֹא יְכוֹלָה לָבוֹא מָחָר.","I can't come tomorrow."]},
 {en:"To want", inf:"Lir-tzot", infHe:"לִרְצוֹת", tr:"Rotze / Rotza", he:"רוֹצֶה / רוֹצָה",
  mn:"roh-TSEH — a waiter leans in: \"Rotze?\" Just ROT-SAY what you want.",
  ex:["Ma at rotza lishtot?","מָה אַתְּ רוֹצָה לִשְׁתּוֹת?","What do you want to drink?"]},
 {en:"To need", inf:"Litz-roch", infHe:"לִצְרוֹךְ", tr:"Tzarich / Tzricha", he:"צָרִיךְ / צְרִיכָה",
  mn:"tsa-REECH — you need to be RICH to afford it. (Tzarich also means \"must\".)",
  ex:["Ani tzarich mafteach chadash.","אֲנִי צָרִיךְ מַפְתֵּחַ חָדָשׁ.","I need a new key."]},
 {en:"To do / to make", inf:"La-a-sot", infHe:"לַעֲשׂוֹת", tr:"Ose / Osa", he:"עוֹשֶׂה / עוֹשָׂה",
  mn:"OH-seh — \"Oh, say…\" Ma ata ose? (\"What are you doing?\") is the most-used question in Israel.",
  ex:["Ma ata ose achshav?","מָה אַתָּה עוֹשֶׂה עַכְשָׁיו?","What are you doing now?"]}]},

{t:"Going and coming", c:"Verbs · Motion", w:[
 {en:"To go / to walk", inf:"La-lechet", infHe:"לָלֶכֶת", tr:"Holech / Holechet", he:"הוֹלֵךְ / הוֹלֶכֶת",
  mn:"ho-LECH — imagine walking and calling \"Hoe! Lech!\" Also: Yalla, lech! = \"Come on, go!\"",
  ex:["Ani holechet la-avoda ba-regel.","אֲנִי הוֹלֶכֶת לָעֲבוֹדָה בָּרֶגֶל.","I walk to work on foot."]},
 {en:"To come", inf:"La-vo", infHe:"לָבוֹא", tr:"Ba / Ba-a", he:"בָּא / בָּאָה",
  mn:"BA — a sheep goes \"baa\" as it comes toward you. Two letters, easiest verb in Hebrew.",
  ex:["Ha-orchim baim be-shesh.","הָאוֹרְחִים בָּאִים בְּשֵׁשׁ.","The guests are coming at six."]},
 {en:"To exit / to go out", inf:"Lat-zet", infHe:"לָצֵאת", tr:"Yotze / Yotzet", he:"יוֹצֵא / יוֹצֵאת",
  mn:"yo-TZEH — the EXIT sign at every Israeli mall says יְצִיאָה (yetzia). \"Yo, TSAY goodbye, I'm out.\"",
  ex:["Anachnu yotzim mi-ha-bayit be-shmoneh.","אֲנַחְנוּ יוֹצְאִים מֵהַבַּיִת בִּשְׁמוֹנֶה.","We leave the house at eight."]},
 {en:"To return (somewhere)", inf:"Lach-zor", infHe:"לַחֲזוֹר", tr:"Chozer / Chozeret", he:"חוֹזֵר / חוֹזֶרֶת",
  mn:"cho-ZER — you return to ZERO, back to the start.",
  ex:["Hu chozer me-ha-tiyul machar.","הוּא חוֹזֵר מֵהַטִּיּוּל מָחָר.","He's coming back from the trip tomorrow."]},
 {en:"To travel (by vehicle)", inf:"Lin-soa", infHe:"לִנְסוֹעַ", tr:"Nosea / Nosaat", he:"נוֹסֵעַ / נוֹסַעַת",
  mn:"no-SEH-a — you travel by NOSE-ing the car forward. Use this for cars/buses; holech is on foot.",
  ex:["Anachnu nosim le-Yerushalayim be-otobus.","אֲנַחְנוּ נוֹסְעִים לִירוּשָׁלַיִם בְּאוֹטוֹבּוּס.","We're traveling to Jerusalem by bus."]}]},

{t:"Moving the body", c:"Verbs · Motion", w:[
 {en:"To run", inf:"La-rutz", infHe:"לָרוּץ", tr:"Ratz / Ratza", he:"רָץ / רָצָה",
  mn:"RATS — rats run. Careful: ratz (runs) vs. rotze (wants) — one vowel apart.",
  ex:["Ha-yeled ratz maher me'od.","הַיֶּלֶד רָץ מַהֵר מְאוֹד.","The boy runs very fast."]},
 {en:"To jump", inf:"Lik-potz", infHe:"לִקְפּוֹץ", tr:"Kofetz / Kofetzet", he:"קוֹפֵץ / קוֹפֶצֶת",
  mn:"KOH-fets — a jumping COFFEE POT rattling on the stove.",
  ex:["Ha-kof kofetz al ha-etz.","הַקּוֹף קוֹפֵץ עַל הָעֵץ.","The monkey jumps on the tree."]},
 {en:"To swim", inf:"Lis-chot", infHe:"לִשְׂחוֹת", tr:"Soche / Socha", he:"שׂוֹחֶה / שׂוֹחָה",
  mn:"SO-cheh — you swim so you don't SOAK and sink. Sounds a bit like \"so-chill\" — floating.",
  ex:["Ani socha ba-agam kol boker.","אֲנִי שׂוֹחָה בָּאֲגַם כָּל בֹּקֶר.","I swim in the lake every morning."]},
 {en:"To dance", inf:"Lir-kod", infHe:"לִרְקוֹד", tr:"Roked / Rokedet", he:"רוֹקֵד / רוֹקֶדֶת",
  mn:"ROH-ked — dancing to ROCK music, in a CODE of steps. Hebrew hora dancing = rikud.",
  ex:["Hem rokdim ba-chatuna kol ha-laila.","הֵם רוֹקְדִים בַּחֲתוּנָה כָּל הַלַּיְלָה.","They dance at the wedding all night."]},
 {en:"To move", inf:"La-zuz", infHe:"לָזוּז", tr:"Zaz / Zaza", he:"זָז / זָזָה",
  mn:"ZAZ — buzz-buzz, something that won't sit still. \"Zuz!\" is what Israelis shout for \"Move it!\"",
  ex:["Al tazuz, ani metzalem!","אַל תָּזוּז, אֲנִי מְצַלֵּם!","Don't move, I'm taking a picture!"]}]},

{t:"The five senses", c:"Verbs · Perception", w:[
 {en:"To see", inf:"Lir-ot", infHe:"לִרְאוֹת", tr:"Ro-eh / Ro-ah", he:"רוֹאֶה / רוֹאָה",
  mn:"ro-EH — a ROE deer that you SEE in the field. Lehitraot (\"see you\") comes from this root.",
  ex:["Ani ro'eh et ha-yam me-ha-chalon.","אֲנִי רוֹאֶה אֶת הַיָּם מֵהַחַלּוֹן.","I see the sea from the window."]},
 {en:"To hear", inf:"Lish-moa", infHe:"לִשְׁמוֹעַ", tr:"Shomea / Shomaat", he:"שׁוֹמֵעַ / שׁוֹמַעַת",
  mn:"sho-MEH-a — \"Shma Yisrael\" — HEAR, O Israel. Same root, ancient and everywhere.",
  ex:["Ata shomea et ha-musika?","אַתָּה שׁוֹמֵעַ אֶת הַמּוּזִיקָה?","Do you hear the music?"]},
 {en:"To listen", inf:"Le-hakshiv", infHe:"לְהַקְשִׁיב", tr:"Makshiv / Makshiva", he:"מַקְשִׁיב / מַקְשִׁיבָה",
  mn:"mak-SHEEV — to listen you have to make it \"SHHH\". Shomea = hear by accident; makshiv = listen on purpose.",
  ex:["Hu lo makshiv li bichlal.","הוּא לֹא מַקְשִׁיב לִי בִּכְלָל.","He doesn't listen to me at all."]},
 {en:"To look / to watch closely", inf:"Le-histakel", infHe:"לְהִסְתַּכֵּל", tr:"Mistakel / Mistakelet", he:"מִסְתַּכֵּל / מִסְתַּכֶּלֶת",
  mn:"mis-ta-KEL — \"Miss, take a look!\" The mis-/mit- start marks a reflexive verb: you turn your own eyes.",
  ex:["Hi mistakelet al ha-tmuna.","הִיא מִסְתַּכֶּלֶת עַל הַתְּמוּנָה.","She's looking at the picture."]},
 {en:"To smell", inf:"Le-hariach", infHe:"לְהָרִיחַ", tr:"Meriach / Mericha", he:"מֵרִיחַ / מְרִיחָה",
  mn:"meh-REE-ach — the smell REACHES your nose. Reach = riach.",
  ex:["Ani meriach lechem tari.","אֲנִי מֵרִיחַ לֶחֶם טָרִי.","I smell fresh bread."]}]},

{t:"Talking, part 1", c:"Verbs · Communication", w:[
 {en:"To speak / to talk", inf:"Le-daber", infHe:"לְדַבֵּר", tr:"Medaber / Medaberet", he:"מְדַבֵּר / מְדַבֶּרֶת",
  mn:"me-da-BER — you talk and talk and it's a lot of DEBRIS/blah-blah. Dibur = speech.",
  ex:["At medaberet ivrit?","אַתְּ מְדַבֶּרֶת עִבְרִית?","Do you speak Hebrew?"]},
 {en:"To say (pt. 2)", inf:"Lo-mar", infHe:"לוֹמַר", tr:"Omer / Omeret", he:"אוֹמֵר / אוֹמֶרֶת",
  mn:"oh-MER — \"Oh, MORE?\" is what you say. This is the everyday \"say\".",
  ex:["Ma at omeret? Ani lo shomea.","מָה אַתְּ אוֹמֶרֶת? אֲנִי לֹא שׁוֹמֵעַ.","What are you saying? I can't hear."]},
 {en:"To say / to tell (pt. 1)", inf:"Le-hagid", infHe:"לְהַגִּיד", tr:"Magid / Magida", he:"מַגִּיד / מַגִּידָה",
  mn:"ma-GID — a maggid was a wandering preacher who went town to town telling stories. Mostly used in the infinitive: Tagid li… = \"Tell me…\"",
  ex:["Tagid li et ha-emet.","תַּגִּיד לִי אֶת הָאֱמֶת.","Tell me the truth."]},
 {en:"To tell / to narrate", inf:"Le-saper", infHe:"לְסַפֵּר", tr:"Mesaper / Mesaperet", he:"מְסַפֵּר / מְסַפֶּרֶת",
  mn:"me-sa-PER — same root as sefer (book) and sipur (story). A story-teller is a sofer/sapar of tales.",
  ex:["Saba mesaper sipurim la-nechadim.","סַבָּא מְסַפֵּר סִפּוּרִים לַנְּכָדִים.","Grandpa tells stories to the grandchildren."]},
 {en:"To ask (a question)", inf:"Li-shol", infHe:"לִשְׁאֹל", tr:"Shoel / Shoelet", he:"שׁוֹאֵל / שׁוֹאֶלֶת",
  mn:"sho-EL — \"Show 'ell, what's the answer?\" She'ela = a question.",
  ex:["Ha-talmid shoel she'ela tova.","הַתַּלְמִיד שׁוֹאֵל שְׁאֵלָה טוֹבָה.","The student asks a good question."]}]},

{t:"Talking, part 2", c:"Verbs · Communication", w:[
 {en:"To ask for / to request", inf:"Le-vakesh", infHe:"לְבַקֵּשׁ", tr:"Mevakesh / Mevakeshet", he:"מְבַקֵּשׁ / מְבַקֶּשֶׁת",
  mn:"me-va-KESH — you request CASH. Bakasha = a request; bevakasha = \"please / here you go\".",
  ex:["Ani mevakeshet mayim, bevakasha.","אֲנִי מְבַקֶּשֶׁת מַיִם, בְּבַקָּשָׁה.","I'm asking for water, please."]},
 {en:"To answer", inf:"La-anot", infHe:"לַעֲנוֹת", tr:"One / Ona", he:"עוֹנֶה / עוֹנָה",
  mn:"OH-neh — \"Oh, NAY\" is still an answer. Tshuva = an answer.",
  ex:["Hi lo ona la-telefon.","הִיא לֹא עוֹנָה לַטֶּלֶפוֹן.","She isn't answering the phone."]},
 {en:"To explain", inf:"Le-hasbir", infHe:"לְהַסְבִּיר", tr:"Masbir / Masbira", he:"מַסְבִּיר / מַסְבִּירָה",
  mn:"mas-BEER — after a couple of BEERS everyone starts explaining everything.",
  ex:["Ha-mora masbira et ha-shiur shuv.","הַמּוֹרָה מַסְבִּירָה אֶת הַשִּׁיעוּר שׁוּב.","The teacher explains the lesson again."]},
 {en:"To shout / to yell", inf:"Litz-ok", infHe:"לִצְעֹק", tr:"Tzoek / Tzoeket", he:"צוֹעֵק / צוֹעֶקֶת",
  mn:"TSO-ek — sounds like a shriek itself: \"tsoh-EK!\" Half a shout, half a squawk.",
  ex:["Al titz'ak, ani lo cheresh!","אַל תִּצְעַק, אֲנִי לֹא חֵרֵשׁ!","Don't shout, I'm not deaf!"]},
 {en:"To be quiet / to shut up", inf:"Lish-tok", infHe:"לִשְׁתּוֹק", tr:"Shotek / Shoteket", he:"שׁוֹתֵק / שׁוֹתֶקֶת",
  mn:"SHO-tek — \"Shhh… take it down.\" Sheket! = \"Quiet!\" — same root.",
  ex:["Kulam shotkim kshe-hu medaber.","כֻּלָּם שׁוֹתְקִים כְּשֶׁהוּא מְדַבֵּר.","Everyone goes quiet when he speaks."]}]},

{t:"The thinking mind", c:"Verbs · Mind", w:[
 {en:"To think", inf:"Lach-shov", infHe:"לַחְשׁוֹב", tr:"Choshev / Choshevet", he:"חוֹשֵׁב / חוֹשֶׁבֶת",
  mn:"cho-SHEV — a machshev is a computer, the thinking machine. Same root: ch-sh-v.",
  ex:["Ani choshevet she-ze ra'ayon tov.","אֲנִי חוֹשֶׁבֶת שֶׁזֶּה רַעְיוֹן טוֹב.","I think it's a good idea."]},
 {en:"To know (a fact)", inf:"La-daat", infHe:"לָדַעַת", tr:"Yodea / Yodaat", he:"יוֹדֵעַ / יוֹדַעַת",
  mn:"yo-DEH-a — \"Yo, DAY-a — do you know what day it is?\" Use for facts and information.",
  ex:["Ani lo yodea eifo ha-mafteach.","אֲנִי לֹא יוֹדֵעַ אֵיפֹה הַמַּפְתֵּחַ.","I don't know where the key is."]},
 {en:"To know (a person) / to be familiar with", inf:"Le-hakir", infHe:"לְהַכִּיר", tr:"Makir / Makira", he:"מַכִּיר / מַכִּירָה",
  mn:"ma-KEER — \"my DEAR\" — the people you know dearly. Never use yodea for people.",
  ex:["At makira et ha-shchena ha-chadasha?","אַתְּ מַכִּירָה אֶת הַשְּׁכֵנָה הַחֲדָשָׁה?","Do you know the new neighbor?"]},
 {en:"To understand", inf:"Le-havin", infHe:"לְהָבִין", tr:"Mevin / Mevina", he:"מֵבִין / מְבִינָה",
  mn:"meh-VEEN — \"Me? BEEN there, so I understand.\"",
  ex:["Ani mevina et ha-mila aval lo et ha-mishpat.","אֲנִי מְבִינָה אֶת הַמִּלָּה אֲבָל לֹא אֶת הַמִּשְׁפָּט.","I understand the word but not the sentence."]},
 {en:"To remember", inf:"Liz-kor", infHe:"לִזְכּוֹר", tr:"Zocher / Zocheret", he:"זוֹכֵר / זוֹכֶרֶת",
  mn:"zo-CHER — \"Yizkor\" is the memorial prayer: remember. Think of a ZOO you'll never forget.",
  ex:["Ata zocher et ha-shem shela?","אַתָּה זוֹכֵר אֶת הַשֵּׁם שֶׁלָּהּ?","Do you remember her name?"]}]},

{t:"Belief and judgement", c:"Verbs · Mind", w:[
 {en:"To forget", inf:"Lish-koach", infHe:"לִשְׁכּוֹחַ", tr:"Shocheach / Shochachat", he:"שׁוֹכֵחַ / שׁוֹכַחַת",
  mn:"sho-KHE-ach — you forgot, so you SHRUG and say \"ach!\" The opposite twin of zocher.",
  ex:["Ani tamid shochachat et ha-mishkafayim.","אֲנִי תָּמִיד שׁוֹכַחַת אֶת הַמִּשְׁקָפַיִם.","I always forget my glasses."]},
 {en:"To believe", inf:"Le-haamin", infHe:"לְהַאֲמִין", tr:"Maamin / Maamina", he:"מַאֲמִין / מַאֲמִינָה",
  mn:"ma-a-MEEN — say AMEN and you're a maamin. Literally the same root: a-m-n.",
  ex:["Ani lo maamin la-sipur ha-ze.","אֲנִי לֹא מַאֲמִין לַסִּפּוּר הַזֶּה.","I don't believe this story."]},
 {en:"To hope", inf:"Le-kavot", infHe:"לְקַוּוֹת", tr:"Mekaveh / Mekava", he:"מְקַוֶּה / מְקַוָּה",
  mn:"me-ka-VEH — same root as Ha-Tikva, \"the hope\", Israel's anthem. Ani mekaveh = \"hopefully\", said constantly.",
  ex:["Ani mekava she-machar yihiyeh cham.","אֲנִי מְקַוָּה שֶׁמָּחָר יִהְיֶה חַם.","I hope tomorrow will be warm."]},
 {en:"To consider / to weigh", inf:"Lish-kol", infHe:"לִשְׁקוֹל", tr:"Shokel / Shokelet", he:"שׁוֹקֵל / שׁוֹקֶלֶת",
  mn:"SHO-kel — the shekel was originally a WEIGHT. To consider is to weigh options — same word, same coin.",
  ex:["Anachnu shoklim laavor le-ir acheret.","אֲנַחְנוּ שׁוֹקְלִים לַעֲבוֹר לְעִיר אַחֶרֶת.","We're considering moving to another city."]},
 {en:"To calculate", inf:"Le-chashev", infHe:"לְחַשֵּׁב", tr:"Mechashev / Mechashevet", he:"מְחַשֵּׁב / מְחַשֶּׁבֶת",
  mn:"me-cha-SHEV — one letter from choshev (thinks). Machshev = computer = the calculating machine.",
  ex:["Hu mechashev kama ze ya'ale.","הוּא מְחַשֵּׁב כַּמָּה זֶה יַעֲלֶה.","He's calculating how much it will cost."]}]},

{t:"School and study", c:"Verbs · Learning", w:[
 {en:"To learn / to study", inf:"Lil-mod", infHe:"לִלְמוֹד", tr:"Lomed / Lomedet", he:"לוֹמֵד / לוֹמֶדֶת",
  mn:"LO-med — you're LOADING your brain, heading for MED school. Talmid (student) is the same root.",
  ex:["Ani lomedet ivrit kol yom.","אֲנִי לוֹמֶדֶת עִבְרִית כָּל יוֹם.","I study Hebrew every day."]},
 {en:"To teach", inf:"Le-lamed", infHe:"לְלַמֵּד", tr:"Melamed / Melamedet", he:"מְלַמֵּד / מְלַמֶּדֶת",
  mn:"me-la-MED — learn is lomed, teach is melamed: add the me- and you're causing someone else to learn.",
  ex:["Ha-more melamed matematika.","הַמּוֹרֶה מְלַמֵּד מָתֵמָטִיקָה.","The teacher teaches math."]},
 {en:"To read", inf:"Li-kro", infHe:"לִקְרוֹא", tr:"Kore / Koret", he:"קוֹרֵא / קוֹרֵאת",
  mn:"ko-REH — the Koran and the Mikra (Hebrew Bible) both mean \"the reading/recitation\". Kore also means \"calls out\".",
  ex:["Hi koret sefer chadash kol shavua.","הִיא קוֹרֵאת סֵפֶר חָדָשׁ כָּל שָׁבוּעַ.","She reads a new book every week."]},
 {en:"To write", inf:"Lich-tov", infHe:"לִכְתּוֹב", tr:"Kotev / Kotevet", he:"כּוֹתֵב / כּוֹתֶבֶת",
  mn:"ko-TEV — think \"quote-ev\": writing down a quote. Michtav (letter) and ketovet (address) share the root.",
  ex:["Ani kotev michtav la-savta sheli.","אֲנִי כּוֹתֵב מִכְתָּב לַסָּבְתָא שֶׁלִּי.","I'm writing a letter to my grandmother."]},
 {en:"To repeat / to go over again", inf:"Lach-zor", infHe:"לַחֲזוֹר", tr:"Chozer / Chozeret", he:"חוֹזֵר / חוֹזֶרֶת",
  mn:"Same verb as \"return\" — in Hebrew, to review is literally to go BACK over the material. Lachzor al ha-chomer = to review.",
  ex:["Ani chozeret al ha-milim ha-yom.","אֲנִי חוֹזֶרֶת עַל הַמִּלִּים הַיּוֹם.","I'm reviewing the words today."]}]},

{t:"Eating and cooking", c:"Verbs · Food", w:[
 {en:"To eat", inf:"Le-e-chol", infHe:"לֶאֱכוֹל", tr:"Ochel / Ochelet", he:"אוֹכֵל / אוֹכֶלֶת",
  mn:"OH-chel — \"Oh, KALE!\" Ochel is also the noun \"food\".",
  ex:["Anachnu ochlim arucha gdola ba-erev.","אֲנַחְנוּ אוֹכְלִים אֲרוּחָה גְּדוֹלָה בָּעֶרֶב.","We eat a big meal in the evening."]},
 {en:"To drink", inf:"Lish-tot", infHe:"לִשְׁתּוֹת", tr:"Shote / Shota", he:"שׁוֹתֶה / שׁוֹתָה",
  mn:"SHO-teh — a SHOT of something to drink.",
  ex:["Hu shote kafe im chalav.","הוּא שׁוֹתֶה קָפֶה עִם חָלָב.","He drinks coffee with milk."]},
 {en:"To cook", inf:"Le-vashel", infHe:"לְבַשֵּׁל", tr:"Mevashel / Mevashelet", he:"מְבַשֵּׁל / מְבַשֶּׁלֶת",
  mn:"me-va-SHEL — cooking in a big SHELL/pot. Tavshil = a cooked dish.",
  ex:["Aba mevashel marak yerakot.","אַבָּא מְבַשֵּׁל מָרָק יְרָקוֹת.","Dad is cooking vegetable soup."]},
 {en:"To bake", inf:"Le-e-fot", infHe:"לֶאֱפוֹת", tr:"Ofe / Ofa", he:"אוֹפֶה / אוֹפָה",
  mn:"OH-feh — \"Oh, fa-fa, it's hot!\" An ofe is also the noun \"baker\".",
  ex:["Ani ofa uga le-yom huledet.","אֲנִי אוֹפָה עוּגָה לְיוֹם הֻלֶּדֶת.","I'm baking a cake for a birthday."]},
 {en:"To taste", inf:"Lit-om", infHe:"לִטְעוֹם", tr:"Toem / Toemet", he:"טוֹעֵם / טוֹעֶמֶת",
  mn:"to-EM — you taste and say \"mmm, TOO YUM.\" Ta'im = tasty.",
  ex:["Tit'ami et ha-rotev, hu metzuyan.","תִּטְעֲמִי אֶת הָרוֹטֶב, הוּא מְצֻיָּן.","Taste the sauce, it's excellent."]}]},

{t:"Everyday routine", c:"Verbs · Daily life", w:[
 {en:"To get up / to stand up", inf:"La-kum", infHe:"לָקוּם", tr:"Kam / Kama", he:"קָם / קָמָה",
  mn:"KAM — \"Come on, get up!\" Kum! is what a parent shouts in the morning.",
  ex:["Ani kama be-shesh ba-boker.","אֲנִי קָמָה בְּשֵׁשׁ בַּבֹּקֶר.","I get up at six in the morning."]},
 {en:"To sit", inf:"La-shevet", infHe:"לָשֶׁבֶת", tr:"Yoshev / Yoshevet", he:"יוֹשֵׁב / יוֹשֶׁבֶת",
  mn:"yo-SHEV — same root as Shabbat, the day you sit and rest. Also moshav, a place people sit/settle.",
  ex:["Anachnu yoshvim ba-salon ve-medabrim.","אֲנַחְנוּ יוֹשְׁבִים בַּסָּלוֹן וּמְדַבְּרִים.","We sit in the living room and talk."]},
 {en:"To stand", inf:"La-amod", infHe:"לַעֲמוֹד", tr:"Omed / Omedet", he:"עוֹמֵד / עוֹמֶדֶת",
  mn:"oh-MED — standing like a column: amud means \"pillar\" (and \"page\").",
  ex:["Hem omdim ba-tor la-kupa.","הֵם עוֹמְדִים בַּתּוֹר לַקֻּפָּה.","They're standing in line for the register."]},
 {en:"To rest", inf:"La-nuach", infHe:"לָנוּחַ", tr:"Nach / Nacha", he:"נָח / נָחָה",
  mn:"NACH — Noah (Noach) rested after the flood. Menucha = rest.",
  ex:["Ani nacha achrei ha-avoda.","אֲנִי נָחָה אַחֲרֵי הָעֲבוֹדָה.","I rest after work."]},
 {en:"To stay / to remain", inf:"Le-hishaer", infHe:"לְהִשָּׁאֵר", tr:"Nishar / Nisheret", he:"נִשְׁאָר / נִשְׁאֶרֶת",
  mn:"nish-AR — what's left over is the SHARE that stays behind.",
  ex:["Ani nisheret ba-bayit ha-erev.","אֲנִי נִשְׁאֶרֶת בַּבַּיִת הָעֶרֶב.","I'm staying home this evening."]}]},

{t:"Giving and taking", c:"Verbs · Hands", w:[
 {en:"To take", inf:"La-kachat", infHe:"לָקַחַת", tr:"Lokeach / Lokachat", he:"לוֹקֵחַ / לוֹקַחַת",
  mn:"lo-KE-ach — \"LOW, CATCH it!\" — reach down and take.",
  ex:["Ani lokachat et ha-yalkut sheli.","אֲנִי לוֹקַחַת אֶת הַיַּלְקוּט שֶׁלִּי.","I'm taking my backpack."]},
 {en:"To give", inf:"La-tet", infHe:"לָתֵת", tr:"Noten / Notenet", he:"נוֹתֵן / נוֹתֶנֶת",
  mn:"no-TEN — \"No? TEN, then\" — handing over ten shekels. Matana (gift) is the same root: n-t-n.",
  ex:["Hu noten li matana yafa.","הוּא נוֹתֵן לִי מַתָּנָה יָפָה.","He's giving me a beautiful gift."]},
 {en:"To bring", inf:"Le-havi", infHe:"לְהָבִיא", tr:"Mevi / Mevia", he:"מֵבִיא / מְבִיאָה",
  mn:"meh-VEE — \"Me? V.I.P. — I bring the goods.\" Related to la-vo (to come): bringing = causing to come.",
  ex:["Ani mevia yayin la-mesiba.","אֲנִי מְבִיאָה יַיִן לַמְּסִבָּה.","I'm bringing wine to the party."]},
 {en:"To put / to place", inf:"La-sim", infHe:"לָשִׂים", tr:"Sam / Sama", he:"שָׂם / שָׂמָה",
  mn:"SAM — \"Sam, put it down.\" Sim lev = \"put heart\" = pay attention.",
  ex:["Sim et ha-sefer al ha-shulchan.","שִׂים אֶת הַסֵּפֶר עַל הַשֻּׁלְחָן.","Put the book on the table."]},
 {en:"To hold", inf:"Le-hachzik", infHe:"לְהַחֲזִיק", tr:"Machzik / Machzika", he:"מַחֲזִיק / מַחֲזִיקָה",
  mn:"mach-ZEEK — you hold on because your grip is chazak (strong). Same root: ch-z-k.",
  ex:["Hi machzika et ha-tinok ba-yadayim.","הִיא מַחֲזִיקָה אֶת הַתִּינוֹק בַּיָּדַיִם.","She's holding the baby in her arms."]}]},

{t:"Fixing and breaking", c:"Verbs · Hands", w:[
 {en:"To open", inf:"Lif-toach", infHe:"לִפְתּוֹחַ", tr:"Poteach / Potachat", he:"פּוֹתֵחַ / פּוֹתַחַת",
  mn:"po-TE-ach — a mafteach (key) opens it. Same root: p-t-ch.",
  ex:["Ha-chanut potachat be-tesha.","הַחֲנוּת פּוֹתַחַת בְּתֵשַׁע.","The store opens at nine."]},
 {en:"To close", inf:"Lis-gor", infHe:"לִסְגּוֹר", tr:"Soger / Sogeret", he:"סוֹגֵר / סוֹגֶרֶת",
  mn:"so-GOR — \"So, GO — we're closing.\" Sagur = closed, on every shop sign.",
  ex:["Bevakasha lisgor et ha-delet.","בְּבַקָּשָׁה לִסְגּוֹר אֶת הַדֶּלֶת.","Please close the door."]},
 {en:"To cut", inf:"Lach-toch", infHe:"לַחְתּוֹךְ", tr:"Chotech / Chotechet", he:"חוֹתֵךְ / חוֹתֶכֶת",
  mn:"cho-TECH — you CHOP with a TECHnique. Chaticha = a piece (something cut off).",
  ex:["Ani chotech et ha-agvania la-salat.","אֲנִי חוֹתֵךְ אֶת הָעַגְבָנִיָּה לַסָּלָט.","I'm cutting the tomato for the salad."]},
 {en:"To break", inf:"Lish-bor", infHe:"לִשְׁבּוֹר", tr:"Shover / Shoveret", he:"שׁוֹבֵר / שׁוֹבֶרֶת",
  mn:"SHO-ver — a SHOVE breaks it. Shavur = broken.",
  ex:["Ha-yeled shover et ha-kos.","הַיֶּלֶד שׁוֹבֵר אֶת הַכּוֹס.","The boy breaks the glass."]},
 {en:"To fix / to repair", inf:"Le-taken", infHe:"לְתַקֵּן", tr:"Metaken / Metakenet", he:"מְתַקֵּן / מְתַקֶּנֶת",
  mn:"me-ta-KEN — \"Me? TAKE 'N fix it.\" Tikkun olam = repairing the world.",
  ex:["Hu metaken et ha-mekarer.","הוּא מְתַקֵּן אֶת הַמְּקָרֵר.","He's fixing the refrigerator."]}]},

{t:"Handling things", c:"Verbs · Hands", w:[
 {en:"To throw", inf:"Liz-rok", infHe:"לִזְרוֹק", tr:"Zorek / Zoreket", he:"זוֹרֵק / זוֹרֶקֶת",
  mn:"ZO-rek — you throw the trash into the WRECK. Lizrok la-zevel = throw in the garbage.",
  ex:["Al tizroki et ze, ze chashuv!","אַל תִּזְרְקִי אֶת זֶה, זֶה חָשׁוּב!","Don't throw that away, it's important!"]},
 {en:"To catch", inf:"Lit-pos", infHe:"לִתְפּוֹס", tr:"Tofes / Tofeset", he:"תּוֹפֵס / תּוֹפֶסֶת",
  mn:"TO-fes — you catch it and it's TOO FAST. Also means \"to grab a seat/spot\".",
  ex:["Ha-kelev tofes et ha-kadur.","הַכֶּלֶב תּוֹפֵס אֶת הַכַּדּוּר.","The dog catches the ball."]},
 {en:"To touch", inf:"La-gaat", infHe:"לָגַעַת", tr:"Nogea / Nogaat", he:"נוֹגֵעַ / נוֹגַעַת",
  mn:"no-GEH-a — \"NO! Get your hands off!\" Al tiga! = \"Don't touch!\"",
  ex:["Asur lagaat ba-tziurim ba-muzeon.","אָסוּר לָגַעַת בַּצִּיּוּרִים בַּמּוּזֵאוֹן.","You mustn't touch the paintings in the museum."]},
 {en:"To arrange / to tidy", inf:"Le-sader", infHe:"לְסַדֵּר", tr:"Mesader / Mesaderet", he:"מְסַדֵּר / מְסַדֶּרֶת",
  mn:"me-sa-DER — you put things in SEDER (order). The Passover Seder is literally \"the order\".",
  ex:["Ani mesaderet et ha-cheder sheli.","אֲנִי מְסַדֶּרֶת אֶת הַחֶדֶר שֶׁלִּי.","I'm tidying my room."]},
 {en:"To divide / to hand out", inf:"Le-chalek", infHe:"לְחַלֵּק", tr:"Mechalek / Mechaleket", he:"מְחַלֵּק / מְחַלֶּקֶת",
  mn:"me-cha-LEK — you divide it into CHALK-marked parts. Chelek = a part.",
  ex:["Ha-mora mechaleket et ha-choveret la-kita.","הַמּוֹרָה מְחַלֶּקֶת אֶת הַחוֹבֶרֶת לַכִּתָּה.","The teacher hands out the booklet to the class."]}]}
];
