/* ===== VERBS, part B — lessons V15–V27 ===== */
const VERBS_B = [
{t:"Loving and laughing", c:"Verbs · Feelings", w:[
 {en:"To like / to love", inf:"Le-ehov", infHe:"לֶאֱהוֹב", tr:"Ohev / Ohevet", he:"אוֹהֵב / אוֹהֶבֶת",
  mn:"oh-HEV — \"Oh! HEAVEN.\" Ahava = love. Ani ohev otach = \"I love you\" (to a woman).",
  ex:["Ani ohev et ha-shir ha-ze me'od.","אֲנִי אוֹהֵב אֶת הַשִּׁיר הַזֶּה מְאוֹד.","I love this song very much."]},
 {en:"To hate", inf:"Lis-no", infHe:"לִשְׂנוֹא", tr:"Sone / Sonet", he:"שׂוֹנֵא / שׂוֹנֵאת",
  mn:"so-NEH — \"So, NAY!\" A hard no. Sin'a = hatred.",
  ex:["Hi sonet lakum mukdam.","הִיא שׂוֹנֵאת לָקוּם מֻקְדָּם.","She hates getting up early."]},
 {en:"To laugh", inf:"Litz-chok", infHe:"לִצְחוֹק", tr:"Tzochek / Tzocheket", he:"צוֹחֵק / צוֹחֶקֶת",
  mn:"TSO-chek — Isaac (Yitzchak) was named for laughter: Sarah laughed when she heard she'd have him. Same root.",
  ex:["Kulam tzochakim me-ha-bdicha shelo.","כֻּלָּם צוֹחֲקִים מֵהַבְּדִיחָה שֶׁלּוֹ.","Everyone laughs at his joke."]},
 {en:"To cry", inf:"Liv-kot", infHe:"לִבְכּוֹת", tr:"Boche / Bocha", he:"בּוֹכֶה / בּוֹכָה",
  mn:"BO-cheh — the sound of a sob, \"boh-heh, boh-heh\". The Western Wall is the Kotel, where people come to cry.",
  ex:["Ha-tinok boche ki hu ra'ev.","הַתִּינוֹק בּוֹכֶה כִּי הוּא רָעֵב.","The baby is crying because he's hungry."]},
 {en:"To enjoy", inf:"Le-henot", infHe:"לֵיהָנוֹת", tr:"Nehene / Nehenet", he:"נֶהֱנֶה / נֶהֱנֵית",
  mn:"neh-heh-NEH — enjoyment is HONEY (hana'a ≈ \"honey-ah\"). Neheneti! = \"I enjoyed it!\"",
  ex:["Anachnu nehenim me-ha-mesiba.","אֲנַחְנוּ נֶהֱנִים מֵהַמְּסִבָּה.","We're enjoying the party."]}]},

{t:"Feelings and kindness", c:"Verbs · Feelings", w:[
 {en:"To feel", inf:"Le-hargish", infHe:"לְהַרְגִּישׁ", tr:"Margish / Margisha", he:"מַרְגִּישׁ / מַרְגִּישָׁה",
  mn:"mar-GEESH — a feeling is a RUSH, spelled backwards-ish. Regesh = an emotion.",
  ex:["Ani margisha yoter tov ha-yom.","אֲנִי מַרְגִּישָׁה יוֹתֵר טוֹב הַיּוֹם.","I feel better today."]},
 {en:"To cuddle / to pamper", inf:"Le-fanek", infHe:"לְפַנֵּק", tr:"Mefanek / Mefaneket", he:"מְפַנֵּק / מְפַנֶּקֶת",
  mn:"me-fa-NEK — you PAMPER by nuzzling someone's NECK. Mefunak = spoiled (in a cute way).",
  ex:["Savta mefaneket et ha-nechadim.","סָבְתָא מְפַנֶּקֶת אֶת הַנְּכָדִים.","Grandma spoils the grandchildren."]},
 {en:"To forgive", inf:"Lis-loach", infHe:"לִסְלוֹחַ", tr:"Soleach / Solachat", he:"סוֹלֵחַ / סוֹלַחַת",
  mn:"so-LE-ach — Slicha! (\"sorry / excuse me\") is the word you'll say twenty times a day. Same root: s-l-ch.",
  ex:["Ani solachat lecha, ze beseder.","אֲנִי סוֹלַחַת לְךָ, זֶה בְּסֵדֶר.","I forgive you, it's fine."]},
 {en:"To wish (someone something)", inf:"Le-achel", infHe:"לְאַחֵל", tr:"Meachel / Meachelet", he:"מְאַחֵל / מְאַחֶלֶת",
  mn:"me-a-CHEL — \"May I A-KHEL you well.\" Note: this is wishing someone something, not wanting (that's rotze).",
  ex:["Ani meachelet lach hatzlacha!","אֲנִי מְאַחֶלֶת לָךְ הַצְלָחָה!","I wish you success!"]},
 {en:"To agree", inf:"Le-haskim", infHe:"לְהַסְכִּים", tr:"Maskim / Maskima", he:"מַסְכִּים / מַסְכִּימָה",
  mn:"mas-KEEM — agreeing to the SCHEME. Haskama = agreement/consent.",
  ex:["Ani maskim itcha legamrei.","אֲנִי מַסְכִּים אִתְּךָ לְגַמְרֵי.","I agree with you completely."]}]},

{t:"Being with people", c:"Verbs · Social", w:[
 {en:"To meet (up with)", inf:"Le-hipagesh", infHe:"לְהִפָּגֵשׁ", tr:"Nifgash / Nifgeshet", he:"נִפְגָּשׁ / נִפְגֶּשֶׁת",
  mn:"nif-GASH — two people meet and GASH into each other. Pgisha = a meeting.",
  ex:["Anachnu nifgashim ba-beit kafe be-arba.","אֲנַחְנוּ נִפְגָּשִׁים בְּבֵית קָפֶה בְּאַרְבַּע.","We're meeting at a café at four."]},
 {en:"To visit", inf:"Le-vaker", infHe:"לְבַקֵּר", tr:"Mevaker / Mevakeret", he:"מְבַקֵּר / מְבַקֶּרֶת",
  mn:"me-va-KER — you drive your CAR to visit. Bikur = a visit; careful, mevaker also means \"criticizes\".",
  ex:["Ani mevakeret et ha-mishpacha be-Chaifa.","אֲנִי מְבַקֶּרֶת אֶת הַמִּשְׁפָּחָה בְּחֵיפָה.","I'm visiting the family in Haifa."]},
 {en:"To help", inf:"La-azor", infHe:"לַעֲזוֹר", tr:"Ozer / Ozeret", he:"עוֹזֵר / עוֹזֶרֶת",
  mn:"oh-ZER — \"Oh, ZORRO to the rescue!\" Ezra = help; ozeret also means \"housekeeper\".",
  ex:["Ata yachol la'azor li bevakasha?","אַתָּה יָכוֹל לַעֲזוֹר לִי בְּבַקָּשָׁה?","Can you help me please?"]},
 {en:"To support", inf:"Lit-moch", infHe:"לִתְמוֹךְ", tr:"Tomech / Tomechet", he:"תּוֹמֵךְ / תּוֹמֶכֶת",
  mn:"TO-mech — a support beam holds up the TOMB. Tmicha = support.",
  ex:["Ha-horim tomchim ba-hachlata shela.","הַהוֹרִים תּוֹמְכִים בַּהַחְלָטָה שֶׁלָּהּ.","The parents support her decision."]},
 {en:"To guard / to watch over", inf:"Lish-mor", infHe:"לִשְׁמוֹר", tr:"Shomer / Shomeret", he:"שׁוֹמֵר / שׁוֹמֶרֶת",
  mn:"SHO-mer — a shomer stands at every Israeli mall entrance. \"Show, MORE security.\"",
  ex:["Ha-shomer shomer al ha-knisa.","הַשּׁוֹמֵר שׁוֹמֵר עַל הַכְּנִיסָה.","The guard watches over the entrance."]}]},

{t:"Work and money", c:"Verbs · Money & work", w:[
 {en:"To work", inf:"La-avod", infHe:"לַעֲבוֹד", tr:"Oved / Ovedet", he:"עוֹבֵד / עוֹבֶדֶת",
  mn:"oh-VED — an OVERWORKED employee. Avoda = work; the root a-v-d also gave us \"slave\" (eved).",
  ex:["Hi ovedet be-misrad gadol.","הִיא עוֹבֶדֶת בְּמִשְׂרָד גָּדוֹל.","She works in a big office."]},
 {en:"To pay", inf:"Le-shalem", infHe:"לְשַׁלֵּם", tr:"Meshalem / Meshalemet", he:"מְשַׁלֵּם / מְשַׁלֶּמֶת",
  mn:"me-sha-LEM — paying makes things SHALEM (whole/complete) — same root as shalom. You settle the debt.",
  ex:["Ani meshalem be-cartis ashrai.","אֲנִי מְשַׁלֵּם בְּכַרְטִיס אַשְׁרַאי.","I'm paying by credit card."]},
 {en:"To buy", inf:"Lik-not", infHe:"לִקְנוֹת", tr:"Kone / Kona", he:"קוֹנֶה / קוֹנָה",
  mn:"KO-neh — you buy an ice cream CONE, eh? Kniya = a purchase; kniyot = shopping.",
  ex:["Anachnu konim yerakot ba-shuk.","אֲנַחְנוּ קוֹנִים יְרָקוֹת בַּשּׁוּק.","We buy vegetables at the market."]},
 {en:"To receive / to get", inf:"Le-kabel", infHe:"לְקַבֵּל", tr:"Mekabel / Mekabelet", he:"מְקַבֵּל / מְקַבֶּלֶת",
  mn:"me-ka-BEL — the Kabbalah is \"the received tradition\". Kabbala is also the receipt you get at a shop.",
  ex:["Kibalti matana yafa. / Ani mekabel michtav.","אֲנִי מְקַבֵּל מִכְתָּב.","I'm receiving a letter."]},
 {en:"To choose", inf:"Liv-chor", infHe:"לִבְחוֹר", tr:"Bocher / Bocheret", he:"בּוֹחֵר / בּוֹחֶרֶת",
  mn:"BO-cher — you choose a BACHELOR from the lineup. Bechira = choice/election.",
  ex:["Kashe li livchor mi-ha-tafrit.","קָשֶׁה לִי לִבְחוֹר מֵהַתַּפְרִיט.","It's hard for me to choose from the menu."]}]},

{t:"Renting, keeping, taking", c:"Verbs · Money & work", w:[
 {en:"To rent (from someone)", inf:"Lis-kor", infHe:"לִשְׂכּוֹר", tr:"Socher / Socheret", he:"שׂוֹכֵר / שׂוֹכֶרֶת",
  mn:"SO-cher — you're the one who SEARCHES for a place. S-ch-r = wages/hire. This is the tenant's verb.",
  ex:["Anachnu socharim dira be-Tel Aviv.","אֲנַחְנוּ שׂוֹכְרִים דִּירָה בְּתֵל אָבִיב.","We're renting an apartment in Tel Aviv."]},
 {en:"To rent out (to someone)", inf:"Le-haskir", infHe:"לְהַשְׂכִּיר", tr:"Maskir / Maskira", he:"מַשְׂכִּיר / מַשְׂכִּירָה",
  mn:"mas-KEER — the ma-/me- prefix makes it causative: you CAUSE someone to rent. This is the landlord's verb.",
  ex:["Hu maskir et ha-dira le-studentim.","הוּא מַשְׂכִּיר אֶת הַדִּירָה לְסְטוּדֶנְטִים.","He rents out the apartment to students."]},
 {en:"To return (something)", inf:"Le-hachzir", infHe:"לְהַחְזִיר", tr:"Machzir / Machzira", he:"מַחְזִיר / מַחְזִירָה",
  mn:"mach-ZEER — chozer = you go back; machzir = you SEND something back. Same pattern as socher/maskir.",
  ex:["Ani machzira et ha-sefer la-sifria.","אֲנִי מַחְזִירָה אֶת הַסֵּפֶר לַסִּפְרִיָּה.","I'm returning the book to the library."]},
 {en:"To keep / to save", inf:"Lish-mor", infHe:"לִשְׁמוֹר", tr:"Shomer / Shomeret", he:"שׁוֹמֵר / שׁוֹמֶרֶת",
  mn:"Same verb as \"to guard\" — in Hebrew, keeping and guarding are one idea. Lishmor al = to take care of.",
  ex:["Ani shomeret et ha-kabalot.","אֲנִי שׁוֹמֶרֶת אֶת הַקַּבָּלוֹת.","I keep the receipts."]},
 {en:"To steal", inf:"Lig-nov", infHe:"לִגְנוֹב", tr:"Gonev / Gonevet", he:"גּוֹנֵב / גּוֹנֶבֶת",
  mn:"GO-nev — a GONIF is Yiddish for a thief, straight from this Hebrew root. \"Lo tignov\" = Thou shalt not steal.",
  ex:["Mishehu ganav li et ha-ofanayim.","מִישֶׁהוּ גָּנַב לִי אֶת הָאוֹפַנַּיִם.","Someone stole my bicycle."]}]},

{t:"Start, continue, stop", c:"Verbs · Change", w:[
 {en:"To begin / to start", inf:"Le-hatchil", infHe:"לְהַתְחִיל", tr:"Matchil / Matchila", he:"מַתְחִיל / מַתְחִילָה",
  mn:"mat-CHEEL — you start and then you CHILL. Hatchala = a beginning.",
  ex:["Ha-seret matchil be-shmoneh.","הַסֶּרֶט מַתְחִיל בִּשְׁמוֹנֶה.","The movie starts at eight."]},
 {en:"To continue", inf:"Le-hamshich", infHe:"לְהַמְשִׁיךְ", tr:"Mamshich / Mamshicha", he:"מַמְשִׁיךְ / מַמְשִׁיכָה",
  mn:"mam-SHEECH — you keep going and it's a long SCHLEP. Hemshech = a sequel/continuation.",
  ex:["Tamshichi lalechet yashar.","תַּמְשִׁיכִי לָלֶכֶת יָשָׁר.","Keep walking straight ahead."]},
 {en:"To finish", inf:"Lig-mor", infHe:"לִגְמֹר", tr:"Gomer / Gomeret", he:"גּוֹמֵר / גּוֹמֶרֶת",
  mn:"GO-mer — \"GO, MORE? No — I'm done.\" Gamarnu! = \"We're finished!\"",
  ex:["Ani gomeret et ha-avoda be-chamesh.","אֲנִי גּוֹמֶרֶת אֶת הָעֲבוֹדָה בְּחָמֵשׁ.","I finish work at five."]},
 {en:"To stop", inf:"La-atzor", infHe:"לַעֲצֹר", tr:"Otzer / Otzeret", he:"עוֹצֵר / עוֹצֶרֶת",
  mn:"oh-TSER — the red octagon says עֲצוֹר (atzor) on every Israeli road. Think \"OH! STOP-zer.\"",
  ex:["Ha-otobus otzer ba-tachana ha-ba'a.","הָאוֹטוֹבּוּס עוֹצֵר בַּתַּחֲנָה הַבָּאָה.","The bus stops at the next station."]},
 {en:"To change", inf:"Le-shanot", infHe:"לְשַׁנּוֹת", tr:"Meshane / Meshana", he:"מְשַׁנֶּה / מְשַׁנָּה",
  mn:"me-sha-NEH — shana = year, and every year things change. Lo meshane = \"it doesn't matter / never mind\".",
  ex:["Hu meshane et ha-tochnit kol yom.","הוּא מְשַׁנֶּה אֶת הַתָּכְנִית כָּל יוֹם.","He changes the plan every day."]}]},

{t:"Becoming and growing", c:"Verbs · Change", w:[
 {en:"To become / to turn into", inf:"La-hafoch", infHe:"לַהֲפוֹךְ", tr:"Hofech / Hofechet", he:"הוֹפֵךְ / הוֹפֶכֶת",
  mn:"HO-fech — to flip something over. Hafuch is the Israeli latte — literally \"upside down\" coffee.",
  ex:["Ha-mayim hofchim le-kerach.","הַמַּיִם הוֹפְכִים לְקֶרַח.","The water turns into ice."]},
 {en:"To grow", inf:"Lig-dol", infHe:"לִגְדּוֹל", tr:"Gadel / Gdela", he:"גָּדֵל / גְּדֵלָה",
  mn:"ga-DEL — one letter from gadol (big). To grow is to become gadol.",
  ex:["Ha-yeladim gdelim kol kach maher.","הַיְּלָדִים גְּדֵלִים כָּל כָּךְ מַהֵר.","The children grow so fast."]},
 {en:"To bloom / to blossom", inf:"Lif-roach", infHe:"לִפְרֹחַ", tr:"Poreach / Porachat", he:"פּוֹרֵחַ / פּוֹרַחַת",
  mn:"po-RE-ach — perach means flower; to bloom is to \"do a flower\". Same root: p-r-ch.",
  ex:["Ha-prachim porchim ba-aviv.","הַפְּרָחִים פּוֹרְחִים בָּאָבִיב.","The flowers bloom in spring."]},
 {en:"To build", inf:"Liv-not", infHe:"לִבְנוֹת", tr:"Bone / Bona", he:"בּוֹנֶה / בּוֹנָה",
  mn:"BO-neh — the BONES of a house. Binyan = a building (and also the name for a Hebrew verb pattern).",
  ex:["Hem bonim bayit chadash ba-shchuna.","הֵם בּוֹנִים בַּיִת חָדָשׁ בַּשְּׁכוּנָה.","They're building a new house in the neighborhood."]},
 {en:"To create", inf:"Li-tzor", infHe:"לִיצוֹר", tr:"Yotzer / Yotzeret", he:"יוֹצֵר / יוֹצֶרֶת",
  mn:"yo-TSER — the Yotzer is the Creator in Hebrew liturgy. Yetzira = a creation/artwork.",
  ex:["Ha-omanit yotzeret muzika chadasha.","הָאָמָּנִית יוֹצֶרֶת מוּזִיקָה חֲדָשָׁה.","The artist creates new music."]}]},

{t:"Searching and finding", c:"Verbs · Investigating", w:[
 {en:"To search / to look for", inf:"Le-chapes", infHe:"לְחַפֵּשׂ", tr:"Mechapes / Mechapeset", he:"מְחַפֵּשׂ / מְחַפֶּשֶׂת",
  mn:"me-cha-PES — searching until you're out of PEP. Chipus = a search.",
  ex:["Ani mechapeset et ha-mishkafayim sheli.","אֲנִי מְחַפֶּשֶׂת אֶת הַמִּשְׁקָפַיִם שֶׁלִּי.","I'm looking for my glasses."]},
 {en:"To find", inf:"Lim-tzo", infHe:"לִמְצוֹא", tr:"Motze / Motzet", he:"מוֹצֵא / מוֹצֵאת",
  mn:"mo-TSEH — \"MAZEL! I found it.\" Metzia = a bargain, literally \"a find\".",
  ex:["Lo motzet et ha-ketovet ba-mapa.","אֲנִי לֹא מוֹצֵאת אֶת הַכְּתֹבֶת בַּמַּפָּה.","I can't find the address on the map."]},
 {en:"To find out / to discover", inf:"Le-galot", infHe:"לְגַלּוֹת", tr:"Megale / Megala", he:"מְגַלֶּה / מְגַלָּה",
  mn:"me-ga-LEH — to un-cover, like a GALLERY revealing a painting. Gilui = a discovery.",
  ex:["Giliti sod. / Ani megale ma kara.","אֲנִי מְגַלֶּה מָה קָרָה.","I'm finding out what happened."]},
 {en:"To check", inf:"Liv-dok", infHe:"לִבְדּוֹק", tr:"Bodek / Bodeket", he:"בּוֹדֵק / בּוֹדֶקֶת",
  mn:"BO-dek — a doctor checks you on the DECK. Bdika = a test/checkup.",
  ex:["Ha-rofe bodek et ha-cholim.","הָרוֹפֵא בּוֹדֵק אֶת הַחוֹלִים.","The doctor examines the patients."]},
 {en:"To include", inf:"Lich-lol", infHe:"לִכְלוֹל", tr:"Kolel / Kolelet", he:"כּוֹלֵל / כּוֹלֶלֶת",
  mn:"KO-lel — from kol (all): to include is to take in ALL of it. Ha-mechir kolel… = \"the price includes…\"",
  ex:["Ha-mechir kolel arucha ve-shtiya.","הַמְּחִיר כּוֹלֵל אֲרוּחָה וּשְׁתִיָּה.","The price includes a meal and a drink."]}]},

{t:"Making and playing", c:"Verbs · Hobbies", w:[
 {en:"To garden", inf:"Le-ganen", infHe:"לְגַנֵּן", tr:"Meganen / Meganenet", he:"מְגַנֵּן / מְגַנֶּנֶת",
  mn:"me-ga-NEN — a gan is a garden (and a kindergarten — a \"children's garden\"). Ganan = gardener.",
  ex:["Saba meganen ba-gan kol shabbat.","סַבָּא מְגַנֵּן בַּגַּן כָּל שַׁבָּת.","Grandpa gardens in the garden every Saturday."]},
 {en:"To paint (a wall, an object)", inf:"Le-tzabo-a", infHe:"לִצְבֹּעַ", tr:"Tzovea / Tzovaat", he:"צוֹבֵעַ / צוֹבַעַת",
  mn:"tso-VEH-a — tzeva = color. To paint is to \"do color\" onto something.",
  ex:["Anachnu tzov'im et ha-kir be-lavan.","אֲנַחְנוּ צוֹבְעִים אֶת הַקִּיר בְּלָבָן.","We're painting the wall white."]},
 {en:"To color (in)", inf:"Litz-bo-a", infHe:"לִצְבֹּעַ", tr:"Tzovea / Tzovaat", he:"צוֹבֵעַ / צוֹבַעַת",
  mn:"Same word as paint — Hebrew doesn't split \"paint\" and \"color\". Context does the work.",
  ex:["Ha-yalda tzovaat et ha-tziur.","הַיַּלְדָּה צוֹבַעַת אֶת הַצִּיּוּר.","The girl colors in the drawing."]},
 {en:"To play (a game)", inf:"Le-sachek", infHe:"לְשַׂחֵק", tr:"Mesachek / Mesacheket", he:"מְשַׂחֵק / מְשַׂחֶקֶת",
  mn:"me-sa-CHEK — you play and you CHECK the score. Mischak = a game; sachkan = a player/actor.",
  ex:["Ha-yeladim mesachakim kaduregel ba-gan.","הַיְּלָדִים מְשַׂחֲקִים כַּדּוּרֶגֶל בַּגַּן.","The children play soccer in the park."]},
 {en:"To sing", inf:"La-shir", infHe:"לָשִׁיר", tr:"Shar / Shara", he:"שָׁר / שָׁרָה",
  mn:"SHAR — shir means \"song\", so lashir = \"to song\". Shir Ha-Shirim = Song of Songs.",
  ex:["Hi shara be-mak-hela.","הִיא שָׁרָה בְּמַקְהֵלָה.","She sings in a choir."]}]},

{t:"Wearing and living", c:"Verbs · Daily life", w:[
 {en:"To wear (clothes)", inf:"Lil-bosh", infHe:"לִלְבּוֹשׁ", tr:"Lovesh / Loveshet", he:"לוֹבֵשׁ / לוֹבֶשֶׁת",
  mn:"LO-vesh — you put on a LOVELY VEST. Levush = attire; malbush = a garment.",
  ex:["Ani loveshet chultza levana la-avoda.","אֲנִי לוֹבֶשֶׁת חֻלְצָה לְבָנָה לָעֲבוֹדָה.","I wear a white shirt to work."]},
 {en:"To wear (shoes) / to lock", inf:"Lin-ol", infHe:"לִנְעֹל", tr:"Noel / Noelet", he:"נוֹעֵל / נוֹעֶלֶת",
  mn:"no-EL — na'al = shoe. Hebrew uses a different verb for footwear than for clothes. (Same root also means \"to lock\" — a shoe closes your foot.)",
  ex:["Hu noel na'alayim shchorot.","הוּא נוֹעֵל נַעֲלַיִם שְׁחוֹרוֹת.","He wears black shoes."]},
 {en:"To live / to reside", inf:"La-gur", infHe:"לָגוּר", tr:"Gar / Gara", he:"גָּר / גָּרָה",
  mn:"GAR — \"Where do you GARage yourself?\" This is where you live; it's not the verb for being alive.",
  ex:["Eifo at gara?","אֵיפֹה אַתְּ גָּרָה?","Where do you live?"]},
 {en:"To use", inf:"Le-hishtamesh", infHe:"לְהִשְׁתַּמֵּשׁ", tr:"Mishtamesh / Mishtameshet", he:"מִשְׁתַּמֵּשׁ / מִשְׁתַּמֶּשֶׁת",
  mn:"mish-ta-MESH — you use a tool until it's a MESH. Shimush = usage; always followed by be-.",
  ex:["Ani mishtameshet ba-machshev la-avoda.","אֲנִי מִשְׁתַּמֶּשֶׁת בַּמַּחְשֵׁב לָעֲבוֹדָה.","I use the computer for work."]},
 {en:"To prefer", inf:"Le-haadif", infHe:"לְהַעֲדִיף", tr:"Maadif / Maadifa", he:"מַעֲדִיף / מַעֲדִיפָה",
  mn:"ma-a-DEEF — the preferred one has the ADvantage — a DIFference in your favor.",
  ex:["Ani maadifa te al kafe.","אֲנִי מַעֲדִיפָה תֵּה עַל קָפֶה.","I prefer tea over coffee."]}]},

{t:"Sending and showing", c:"Verbs · Communication", w:[
 {en:"To send", inf:"Lish-loach", infHe:"לִשְׁלוֹחַ", tr:"Sholeach / Sholachat", he:"שׁוֹלֵחַ / שׁוֹלַחַת",
  mn:"sho-LE-ach — a shaliach is a messenger, one who is SENT. \"Show, LAUNCH it.\"",
  ex:["Ani sholachat lach hoda'a.","אֲנִי שׁוֹלַחַת לָךְ הוֹדָעָה.","I'm sending you a message."]},
 {en:"To show", inf:"Le-harot", infHe:"לְהַרְאוֹת", tr:"Mar-e / Mar-a", he:"מַרְאֶה / מַרְאָה",
  mn:"mar-EH — ro'eh = see, mar'eh = cause to see = show. Mar'a also means \"mirror\".",
  ex:["Tar'e li et ha-tmunot me-ha-tiyul.","תַּרְאֶה לִי אֶת הַתְּמוּנוֹת מֵהַטִּיּוּל.","Show me the pictures from the trip."]},
 {en:"To sign", inf:"Lach-tom", infHe:"לַחְתּוֹם", tr:"Chotem / Chotemet", he:"חוֹתֵם / חוֹתֶמֶת",
  mn:"cho-TEM — a chotemet is a rubber stamp. You sign or stamp to seal it.",
  ex:["Tachtemi po, bevakasha.","תַּחְתְּמִי פֹּה, בְּבַקָּשָׁה.","Sign here, please."]},
 {en:"To try", inf:"Le-nasot", infHe:"לְנַסּוֹת", tr:"Menase / Menasa", he:"מְנַסֶּה / מְנַסָּה",
  mn:"me-na-SEH — trying is a NUISANCE until it works. Nisayon = an attempt (and \"experience\").",
  ex:["Ani menasa lehavin et ha-dikduk.","אֲנִי מְנַסָּה לְהָבִין אֶת הַדִּקְדּוּק.","I'm trying to understand the grammar."]},
 {en:"To interpret / to explain the meaning", inf:"Le-faresh", infHe:"לְפָרֵשׁ", tr:"Mefaresh / Mefareshet", he:"מְפָרֵשׁ / מְפָרֶשֶׁת",
  mn:"me-fa-RESH — Rashi, the great biblical commentator, is the parshan par excellence. Parasha = a portion/interpretation.",
  ex:["Kol echad mefaresh et ze acheret.","כָּל אֶחָד מְפָרֵשׁ אֶת זֶה אַחֶרֶת.","Everyone interprets it differently."]}]},

{t:"Trouble and mishaps", c:"Verbs · Things going wrong", w:[
 {en:"To fall", inf:"Li-pol", infHe:"לִפּוֹל", tr:"Nofel / Nofelet", he:"נוֹפֵל / נוֹפֶלֶת",
  mn:"no-FEL — \"NO! FELL!\" Nefila = a fall.",
  ex:["Ha-alim noflim ba-stav.","הֶעָלִים נוֹפְלִים בַּסְּתָיו.","The leaves fall in autumn."]},
 {en:"To hurt / to harm", inf:"Lif-goa", infHe:"לִפְגּוֹעַ", tr:"Pogea / Pogaat", he:"פּוֹגֵעַ / פּוֹגַעַת",
  mn:"po-GEH-a — a POKE that hurts. Pgi'a = an injury or an offense — it covers hurting feelings too.",
  ex:["Ha-milim shelo pog'ot bi.","הַמִּלִּים שֶׁלּוֹ פּוֹגְעוֹת בִּי.","His words hurt me."]},
 {en:"To run away / to escape", inf:"Liv-roach", infHe:"לִבְרוֹחַ", tr:"Boreach / Borachat", he:"בּוֹרֵחַ / בּוֹרַחַת",
  mn:"bo-RE-ach — \"BOLT, ROACH!\" — a cockroach scurrying off when the light goes on.",
  ex:["Ha-chatul boreach me-ha-kelev.","הֶחָתוּל בּוֹרֵחַ מֵהַכֶּלֶב.","The cat runs away from the dog."]},
 {en:"To bark", inf:"Lin-boach", infHe:"לִנְבּוֹחַ", tr:"Noveach / Novachat", he:"נוֹבֵחַ / נוֹבַחַת",
  mn:"no-VEH-ach — it even sounds like a dog: \"no-VACH! no-VACH!\"",
  ex:["Ha-kelev noveach al kol adam.","הַכֶּלֶב נוֹבֵחַ עַל כָּל אָדָם.","The dog barks at every person."]},
 {en:"To stare", inf:"Liv-hot", infHe:"לִבְהוֹת", tr:"Bo-he / Bo-ha", he:"בּוֹהֶה / בּוֹהָה",
  mn:"BO-heh — a blank, BORED \"boh…\" while you gaze into nothing.",
  ex:["Hu bohe ba-kir mizman.","הוּא בּוֹהֶה בַּקִּיר מִזְּמַן.","He's been staring at the wall for a while."]}]},

{t:"Leaving and passing by", c:"Verbs · Motion", w:[
 {en:"To leave (a place or person)", inf:"La-azov", infHe:"לַעֲזוֹב", tr:"Ozev / Ozevet", he:"עוֹזֵב / עוֹזֶבֶת",
  mn:"oh-ZEV — \"Azov oti!\" = \"Leave me alone!\" One of the most-heard phrases in Israel.",
  ex:["Hi ozevet et ha-avoda be-shesh.","הִיא עוֹזֶבֶת אֶת הָעֲבוֹדָה בְּשֵׁשׁ.","She leaves work at six."]},
 {en:"To pass / to cross / to move house", inf:"La-avor", infHe:"לַעֲבוֹר", tr:"Over / Overet", he:"עוֹבֵר / עוֹבֶרֶת",
  mn:"oh-VER — you go OVER to the other side. Avar = the past (what has passed); Ivrit = Hebrew, the language of those who crossed over.",
  ex:["Ha-zman over maher.","הַזְּמַן עוֹבֵר מַהֵר.","Time passes quickly."]},
 {en:"To watch (a film, a show)", inf:"Litz-pot", infHe:"לִצְפּוֹת", tr:"Tzofe / Tzofa", he:"צוֹפֶה / צוֹפָה",
  mn:"TSO-feh — a tzofe is a scout/lookout. Use this for screens; mistakel is for looking at things.",
  ex:["Anachnu tzofim be-seret ha-erev.","אֲנַחְנוּ צוֹפִים בְּסֶרֶט הָעֶרֶב.","We're watching a movie tonight."]},
 {en:"To sanctify / to bless (kiddush)", inf:"Le-kadesh", infHe:"לְקַדֵּשׁ", tr:"Mekadesh / Mekadeshet", he:"מְקַדֵּשׁ / מְקַדֶּשֶׁת",
  mn:"me-ka-DESH — kadosh = holy; Kiddush is the Friday-night blessing over wine. Same root: k-d-sh.",
  ex:["Aba mekadesh al ha-yayin be-erev shabbat.","אַבָּא מְקַדֵּשׁ עַל הַיַּיִן בְּעֶרֶב שַׁבָּת.","Dad makes kiddush over the wine on Friday night."]}]}
];
