/* ===== NOUNS, part A — animals, body, family ===== */
const NOUNS_A = [
{t:"Farm animals", c:"Nouns · Animals", w:[
 {en:"Bear", tr:"Dov / Dova", he:"דֹּב / דֻּבָּה", pl:"Dubim / Dubot", plHe:"דֻּבִּים / דֻּבּוֹת",
  mn:"DOV — a bear is big enough to eat a DOVE in one bite. (Handy: the two are almost the same sound — dov / yona.)",
  ex:["Ha-dov gadol ve-chazak.","הַדֹּב גָּדוֹל וְחָזָק.","The bear is big and strong."]},
 {en:"Bull", tr:"Par", he:"פַּר", pl:"Parim", plHe:"פָּרִים",
  mn:"PAR — a bull runs at PAR speed. Note pair: par (bull) / para (cow) — just add the -a for female.",
  ex:["Ha-par ratz ba-sadeh.","הַפַּר רָץ בַּשָּׂדֶה.","The bull runs in the field."]},
 {en:"Cow", tr:"Para", he:"פָּרָה", pl:"Parot", plHe:"פָּרוֹת",
  mn:"pa-RA — the cow says \"pa-RAAA\" instead of moo. The Red Heifer of the Torah is the Para Aduma.",
  ex:["Ha-para notenet chalav.","הַפָּרָה נוֹתֶנֶת חָלָב.","The cow gives milk."]},
 {en:"Donkey", tr:"Chamor", he:"חֲמוֹר", pl:"Chamorim", plHe:"חֲמוֹרִים",
  mn:"cha-MOR — the donkey wants CHA-MORE hay. Calling someone a chamor is a classic Israeli insult.",
  ex:["Ha-chamor noseh mit'an kaved.","הַחֲמוֹר נוֹשֵׂא מִטְעָן כָּבֵד.","The donkey carries a heavy load."]},
 {en:"Monkey", tr:"Kof", he:"קוֹף", pl:"Kofim", plHe:"קוֹפִים",
  mn:"KOF — a monkey with a COUGH. Also the name of the Hebrew letter ק.",
  ex:["Ha-kof ochel banana ba-gan chayot.","הַקּוֹף אוֹכֵל בַּנָנָה בְּגַן חַיּוֹת.","The monkey eats a banana at the zoo."]}]},

{t:"Small creatures", c:"Nouns · Animals", w:[
 {en:"Rabbit", tr:"Shafan", he:"שָׁפָן", pl:"Shfanim", plHe:"שְׁפָנִים",
  mn:"sha-FAN — a rabbit is a big FAN of carrots. (Shafan also means \"coward\" in slang.)",
  ex:["Ha-shafan ochel gezer.","הַשָּׁפָן אוֹכֵל גֶּזֶר.","The rabbit eats a carrot."]},
 {en:"Mouse", tr:"Achbar", he:"עַכְבָּר", pl:"Achbarim", plHe:"עַכְבָּרִים",
  mn:"ach-BAR — a mouse sneaking into the BAR. Also the word for a computer mouse.",
  ex:["Yesh achbar ba-mitbach!","יֵשׁ עַכְבָּר בַּמִּטְבָּח!","There's a mouse in the kitchen!"]},
 {en:"Snake", tr:"Nachash", he:"נָחָשׁ", pl:"Nechashim", plHe:"נְחָשִׁים",
  mn:"na-CHASH — hear the hiss in the -CHASH. The serpent in Eden is Ha-Nachash.",
  ex:["Ha-nachash mesukan me'od.","הַנָּחָשׁ מְסֻכָּן מְאוֹד.","The snake is very dangerous."]},
 {en:"Turtle", tr:"Tsav", he:"צָב", pl:"Tsavim", plHe:"צַבִּים",
  mn:"TSAV — short and squat, like the turtle itself. Sounds like \"tsov\" — slow.",
  ex:["Ha-tsav holech le'at me'od.","הַצָּב הוֹלֵךְ לְאַט מְאוֹד.","The turtle walks very slowly."]},
 {en:"Spider", tr:"Akavish", he:"עַכָּבִישׁ", pl:"Akavishim", plHe:"עַכָּבִישִׁים",
  mn:"a-ka-VEESH — \"a-ka-VEESH\" sounds like a web being spun. Kurei akavish = a spider's web.",
  ex:["Yesh akavish gadol ba-pina.","יֵשׁ עַכָּבִישׁ גָּדוֹל בַּפִּנָּה.","There's a big spider in the corner."]}]},

{t:"Bugs and birds", c:"Nouns · Animals", w:[
 {en:"Butterfly", tr:"Parpar", he:"פַּרְפַּר", pl:"Parparim", plHe:"פַּרְפָּרִים",
  mn:"par-PAR — say it twice like the two flapping wings: par-par, par-par.",
  ex:["Ha-parpar tzivoni ve-yafe.","הַפַּרְפַּר צִבְעוֹנִי וְיָפֶה.","The butterfly is colorful and beautiful."]},
 {en:"Fly", tr:"Zvuv", he:"זְבוּב", pl:"Zvuvim", plHe:"זְבוּבִים",
  mn:"ZVOOV — it literally buzzes: zvoov-zvoov.",
  ex:["Ha-zvuv me'atzben oti.","הַזְּבוּב מְעַצְבֵּן אוֹתִי.","The fly is annoying me."]},
 {en:"Insect / bug", tr:"Cherek (slang: Juk)", he:"חֶרֶק", pl:"Charakim", plHe:"חֲרָקִים",
  mn:"CHEH-rek — a bug that wrecks your picnic. Juk is the everyday slang word for a cockroach.",
  ex:["Yesh harbeh charakim ba-gina.","יֵשׁ הַרְבֵּה חֲרָקִים בַּגִּנָּה.","There are a lot of insects in the garden."]},
 {en:"Chick (baby bird)", tr:"Gozal", he:"גּוֹזָל", pl:"Gozalim", plHe:"גּוֹזָלִים",
  mn:"go-ZAL — a fluffy chick that GOES ALL over the place. Israelis call a cute kid a gozal.",
  ex:["Ha-gozal nofel me-ha-ken.","הַגּוֹזָל נוֹפֵל מֵהַקֵּן.","The chick falls from the nest."]},
 {en:"Chicken / rooster (animal)", tr:"Tarnegol / Tarnegolet", he:"תַּרְנְגוֹל / תַּרְנְגוֹלֶת", pl:"Tarnegolim / Tarnegolot", plHe:"תַּרְנְגוֹלִים / תַּרְנְגוֹלוֹת",
  mn:"tar-ne-GOL — a rooster crowing a long \"tar-ne-GOOOL\" at dawn. The -et ending makes it the hen.",
  ex:["Ha-tarnegol koreh ba-boker.","הַתַּרְנְגוֹל קוֹרֵא בַּבֹּקֶר.","The rooster crows in the morning."]}]},

{t:"Birds and pets", c:"Nouns · Animals", w:[
 {en:"Dove / pigeon", tr:"Yona", he:"יוֹנָה", pl:"Yonim", plHe:"יוֹנִים",
  mn:"yo-NA — Jonah (Yonah) in the Bible is literally named \"dove\". Noah's dove was a yona too.",
  ex:["Ha-yona omedet al ha-gag.","הַיּוֹנָה עוֹמֶדֶת עַל הַגַּג.","The dove is standing on the roof."]},
 {en:"Duck", tr:"Barvaz / Barvaza", he:"בַּרְוָז / בַּרְוָזָה", pl:"Barvazim / Barvazot", plHe:"בַּרְוָזִים / בַּרְוָזוֹת",
  mn:"bar-VAZ — a duck waddling into a BAR with a VASE. Silly enough to stick.",
  ex:["Ha-barvazim sochim ba-agam.","הַבַּרְוָזִים שׂוֹחִים בָּאֲגַם.","The ducks swim in the lake."]},
 {en:"Eagle / vulture", tr:"Nesher", he:"נֶשֶׁר", pl:"Nesharim", plHe:"נְשָׁרִים",
  mn:"NEH-sher — a NASHER that snatches its prey. Israel's rescue helicopters and a whole town are named Nesher.",
  ex:["Ha-nesher af gavoha ba-shamayim.","הַנֶּשֶׁר עָף גָּבוֹהַּ בַּשָּׁמַיִם.","The eagle flies high in the sky."]},
 {en:"Owl", tr:"Yanshuf", he:"יַנְשׁוּף", pl:"Yanshufim", plHe:"יַנְשׁוּפִים",
  mn:"yan-SHOOF — an owl going \"shoof… shoof…\" in the night. (Handily, shuf is Arabic slang for \"look\" — the owl is all eyes.)",
  ex:["Ha-yanshuf er kol ha-laila.","הַיַּנְשׁוּף עֵר כָּל הַלַּיְלָה.","The owl is awake all night."]},
 {en:"Pet", tr:"Chayat machmad", he:"חַיַּת מַחְמָד", pl:"Chayot machmad", plHe:"חַיּוֹת מַחְמָד",
  mn:"chai-YAT mach-MAD — chaya = animal, machmad = darling/delight. A \"darling animal\".",
  ex:["Yesh lachem chayat machmad ba-bayit?","יֵשׁ לָכֶם חַיַּת מַחְמָד בַּבַּיִת?","Do you have a pet at home?"]},
 {en:"Tail", tr:"Zanav", he:"זָנָב", pl:"Zenavot", plHe:"זְנָבוֹת",
  mn:"za-NAV — the tail NAVigates the animal. Also: a zanav is the \"tail end\" of a line.",
  ex:["La-kelev yesh zanav aroch.","לַכֶּלֶב יֵשׁ זָנָב אָרוֹךְ.","The dog has a long tail."]}]},

{t:"The face", c:"Nouns · Body", w:[
 {en:"Head", tr:"Rosh", he:"רֹאשׁ", pl:"Rashim", plHe:"רָאשִׁים",
  mn:"ROSH — Rosh Hashanah = \"head of the year\". Rosh is also a boss or a chief.",
  ex:["Ko'ev li ha-rosh.","כּוֹאֵב לִי הָרֹאשׁ.","My head hurts."]},
 {en:"Hair", tr:"Se-ar", he:"שֵׂעָר", pl:"—", plHe:"—",
  mn:"seh-AR — think of a SHEAR, the tool for cutting hair. Usually used as a collective, no plural.",
  ex:["Yesh la se'ar aroch ve-shachor.","יֵשׁ לָהּ שֵׂעָר אָרוֹךְ וְשָׁחוֹר.","She has long black hair."]},
 {en:"Eye", tr:"Ayin", he:"עַיִן", pl:"Enayim", plHe:"עֵינַיִם",
  mn:"AH-yin — think of the \"evil eye\" charm, the ayin hara. Body parts that come in twos take the -ayim ending.",
  ex:["Yesh lo enayim yerukot.","יֵשׁ לוֹ עֵינַיִם יְרֻקּוֹת.","He has green eyes."]},
 {en:"Ear", tr:"Ozen", he:"אֹזֶן", pl:"Oznayim", plHe:"אָזְנַיִם",
  mn:"OH-zen — hamantaschen are called oznei Haman, \"Haman's ears\". Note the -ayim pair ending again.",
  ex:["Ha-oznayim sheli ko'avot ba-matos.","הָאָזְנַיִם שֶׁלִּי כּוֹאֲבוֹת בַּמָּטוֹס.","My ears hurt on the plane."]},
 {en:"Nose", tr:"Af", he:"אַף", pl:"Apayim", plHe:"אַפַּיִם",
  mn:"AF — one syllable, like a sniff. Af also means \"not even / none at all\": af echad = nobody.",
  ex:["Ha-af sheli satum.","הָאַף שֶׁלִּי סָתוּם.","My nose is blocked."]}]},

{t:"Mouth and mind", c:"Nouns · Body", w:[
 {en:"Mouth", tr:"Peh", he:"פֶּה", pl:"Piyot", plHe:"פִּיּוֹת",
  mn:"PEH — the sound your mouth makes spitting something out: \"peh!\" Also the letter פ.",
  ex:["Tiftach et ha-peh, bevakasha.","תִּפְתַּח אֶת הַפֶּה, בְּבַקָּשָׁה.","Open your mouth, please."]},
 {en:"Tooth", tr:"Shen", he:"שֵׁן", pl:"Shinayim", plHe:"שִׁנַּיִם",
  mn:"SHEN — you SHINE your teeth. A dentist is a rofe shinayim, a \"teeth doctor\".",
  ex:["Ani mtzachtzeach shinayim pa'amayim be-yom.","אֲנִי מְצַחְצֵחַ שִׁנַּיִם פַּעֲמַיִם בְּיוֹם.","I brush my teeth twice a day."]},
 {en:"Eyebrow", tr:"Gaba", he:"גַּבָּה", pl:"Gabot", plHe:"גַּבּוֹת",
  mn:"ga-BA — from gav (back): the eyebrow is the \"back\" or ridge above the eye.",
  ex:["Hi merima gaba be-hafta'a.","הִיא מְרִימָה גַּבָּה בְּהַפְתָּעָה.","She raises an eyebrow in surprise."]},
 {en:"Brain", tr:"Moach", he:"מוֹחַ", pl:"Mochot", plHe:"מוֹחוֹת",
  mn:"MO-ach — \"MORE, ACH!\" — the organ that always wants more. Slang: yesh lo moach = \"he's smart\".",
  ex:["Ha-moach shel ha-adam mesubach.","הַמּוֹחַ שֶׁל הָאָדָם מְסֻבָּךְ.","The human brain is complicated."]},
 {en:"Skin / leather", tr:"Or", he:"עוֹר", pl:"—", plHe:"—",
  mn:"OR — careful: or (עוֹר) = skin, but or (אוֹר) = light. Same sound, different first letter.",
  ex:["Yesh li or ragish la-shemesh.","יֵשׁ לִי עוֹר רָגִישׁ לַשֶּׁמֶשׁ.","I have skin that's sensitive to the sun."]}]},

{t:"Arms and torso", c:"Nouns · Body", w:[
 {en:"Hand / arm", tr:"Yad", he:"יָד", pl:"Yadayim", plHe:"יָדַיִם",
  mn:"YAD — the hamsa charm is also called a yad. The Torah pointer is a yad too — a little hand.",
  ex:["Tirchatz yadayim lifnei ha-arucha.","תִּרְחַץ יָדַיִם לִפְנֵי הָאֲרוּחָה.","Wash your hands before the meal."]},
 {en:"Finger", tr:"Etzba", he:"אֶצְבַּע", pl:"Etzbaot", plHe:"אֶצְבָּעוֹת",
  mn:"ETS-ba — \"ETS-BAH!\" — the sound of poking someone with a finger.",
  ex:["Chatachti et ha-etzba ba-mitbach.","חָתַכְתִּי אֶת הָאֶצְבַּע בַּמִּטְבָּח.","I cut my finger in the kitchen."]},
 {en:"Shoulder", tr:"Katef", he:"כָּתֵף", pl:"Ktefayim", plHe:"כְּתֵפַיִם",
  mn:"ka-TEF — you carry a bag on your shoulder, so it's the \"CARRY-TEF\". K-t-f is the root for carrying on the shoulder.",
  ex:["Ha-katef sheli ko'evet me-ha-yalkut.","הַכָּתֵף שֶׁלִּי כּוֹאֶבֶת מֵהַיַּלְקוּט.","My shoulder hurts from the backpack."]},
 {en:"Back", tr:"Gav", he:"גַּב", pl:"Gavim", plHe:"גַּבִּים",
  mn:"GAV — think \"GIVE me a back rub\". Also the root of gaba (eyebrow) — a ridge.",
  ex:["Ko'ev li ha-gav mi-ha-yeshiva.","כּוֹאֵב לִי הַגַּב מֵהַיְּשִׁיבָה.","My back hurts from sitting."]},
 {en:"Chest", tr:"Chaze", he:"חָזֶה", pl:"Chazot", plHe:"חָזוֹת",
  mn:"cha-ZEH — related to chazak (strong) in sound: a strong chest. Also the word for chicken breast on a menu.",
  ex:["Chaze of im yerakot, bevakasha.","חֲזֵה עוֹף עִם יְרָקוֹת, בְּבַקָּשָׁה.","Chicken breast with vegetables, please."]}]},

{t:"Legs and insides", c:"Nouns · Body", w:[
 {en:"Leg / foot", tr:"Regel", he:"רֶגֶל", pl:"Raglaim", plHe:"רַגְלַיִם",
  mn:"REH-gel — you get around on a REGULAR pair of legs. Ba-regel = \"on foot\"; kaduregel = soccer, \"foot-ball\".",
  ex:["Ani holech la-chanut ba-regel.","אֲנִי הוֹלֵךְ לַחֲנוּת בָּרֶגֶל.","I walk to the store on foot."]},
 {en:"Foot (the sole)", tr:"Kaf regel", he:"כַּף רֶגֶל", pl:"Kapot raglaim", plHe:"כַּפּוֹת רַגְלַיִם",
  mn:"kaf = a scoop or palm. Your foot is literally \"the scoop of the leg\" — and kaf yad is the palm of your hand.",
  ex:["Ha-chol cham al kapot ha-raglaim.","הַחוֹל חַם עַל כַּפּוֹת הָרַגְלַיִם.","The sand is hot on the soles of my feet."]},
 {en:"Toe", tr:"Etzba regel", he:"אֶצְבַּע רֶגֶל", pl:"Etzbaot raglaim", plHe:"אֶצְבְּעוֹת רַגְלַיִם",
  mn:"Hebrew has no separate word for \"toe\" — it's just a \"finger of the leg\". Nice and logical.",
  ex:["Nifga'ti ba-etzba regel ba-delet.","נִפְגַּעְתִּי בְּאֶצְבַּע רֶגֶל בַּדֶּלֶת.","I hurt my toe on the door."]},
 {en:"Knee", tr:"Berech", he:"בֶּרֶךְ", pl:"Birkayim", plHe:"בִּרְכַּיִם",
  mn:"BEH-rech — the same root as bracha (blessing): you bend the knee to bless. Baruch = blessed.",
  ex:["Ha-birkayim sheli ko'avot achrei ha-ritza.","הַבִּרְכַּיִם שֶׁלִּי כּוֹאֲבוֹת אַחֲרֵי הָרִיצָה.","My knees hurt after the run."]},
 {en:"Heart", tr:"Lev", he:"לֵב", pl:"Levavot", plHe:"לְבָבוֹת",
  mn:"LEV — LOVE with a V. Sim lev = \"pay attention\" (literally \"put heart\").",
  ex:["Yesh la lev tov.","יֵשׁ לָהּ לֵב טוֹב.","She has a good heart."]}]},

{t:"The whole body", c:"Nouns · Body", w:[
 {en:"Body", tr:"Guf", he:"גּוּף", pl:"Gufim", plHe:"גּוּפִים",
  mn:"GOOF — your body is a big GOOFY machine. Guf also means \"grammatical person\" (first person = guf rishon).",
  ex:["Chashuv lishmor al ha-guf.","חָשׁוּב לִשְׁמוֹר עַל הַגּוּף.","It's important to take care of your body."]},
 {en:"Bone", tr:"Etzem", he:"עֶצֶם", pl:"Atzamot", plHe:"עֲצָמוֹת",
  mn:"EH-tsem — etzem also means \"an object\" or \"the essence of a thing\": be-etzem = \"actually, in essence\".",
  ex:["Ha-kelev ochel etzem ba-gina.","הַכֶּלֶב אוֹכֵל עֶצֶם בַּגִּנָּה.","The dog eats a bone in the garden."]},
 {en:"Stomach", tr:"Keva", he:"קֵבָה", pl:"Kevot", plHe:"קֵבוֹת",
  mn:"KEH-va — think \"CAVE-ah\": the cave where your food goes.",
  ex:["Ko'evet li ha-keva achrei ha-arucha.","כּוֹאֶבֶת לִי הַקֵּבָה אַחֲרֵי הָאֲרוּחָה.","My stomach hurts after the meal."]},
 {en:"Person (man / woman)", tr:"Gever / Isha", he:"גֶּבֶר / אִשָּׁה", pl:"Gvarim / Nashim", plHe:"גְּבָרִים / נָשִׁים",
  mn:"GEH-ver — a gever is a \"man's man\"; gvura = heroism. Isha = woman, from the same root as ish (man/person). Note the irregular plural nashim.",
  ex:["Yesh shlosha gvarim ve-shtei nashim ba-cheder.","יֵשׁ שְׁלוֹשָׁה גְּבָרִים וּשְׁתֵּי נָשִׁים בַּחֶדֶר.","There are three men and two women in the room."]}]},

{t:"The immediate family", c:"Nouns · Family", w:[
 {en:"Baby", tr:"Tinok / Tinoket", he:"תִּינוֹק / תִּינוֹקֶת", pl:"Tinokim / Tinokot", plHe:"תִּינוֹקִים / תִּינוֹקוֹת",
  mn:"tee-NOK — a baby gives a little \"TINY KNOCK\" on the world.",
  ex:["Ha-tinoket yeshena ba-mita.","הַתִּינוֹקֶת יְשֵׁנָה בַּמִּטָּה.","The baby girl is sleeping in the bed."]},
 {en:"Brother", tr:"Ach", he:"אָח", pl:"Achim", plHe:"אַחִים",
  mn:"ACH — \"Ach sheli!\" (\"my brother!\") is how Israeli men greet each other. Also the sound of a sigh.",
  ex:["Yesh li ach echad ve-shtei achayot.","יֵשׁ לִי אָח אֶחָד וּשְׁתֵּי אֲחָיוֹת.","I have one brother and two sisters."]},
 {en:"Sister", tr:"Achot", he:"אָחוֹת", pl:"Achayot", plHe:"אַחְיוֹת",
  mn:"a-CHOT — brother + the feminine -ot. Achot also means \"nurse\" in a hospital.",
  ex:["Ha-achot sheli gara be-Chaifa.","הָאָחוֹת שֶׁלִּי גָּרָה בְּחֵיפָה.","My sister lives in Haifa."]},
 {en:"Husband / owner", tr:"Ba-al", he:"בַּעַל", pl:"Bealim", plHe:"בְּעָלִים",
  mn:"BA-al — Baal was the Canaanite \"lord\". A ba'al is a master or owner — and, old-fashionedly, a husband.",
  ex:["Ha-ba'al shela mevashel metzuyan.","הַבַּעַל שֶׁלָּהּ מְבַשֵּׁל מְצֻיָּן.","Her husband cooks excellently."]},
 {en:"Partner / roommate", tr:"Shutaf / Shutafa", he:"שׁוּתָף / שׁוּתָפָה", pl:"Shutafim / Shutafot", plHe:"שׁוּתָפִים / שׁוּתָפוֹת",
  mn:"shu-TAF — you SHARE the TAB. Shutafut = a partnership.",
  ex:["Ha-shutafa sheli le-dira me'od nekiya.","הַשּׁוּתָפָה שֶׁלִּי לְדִירָה מְאוֹד נְקִיָּה.","My apartment roommate is very clean."]}]},

{t:"In-laws", c:"Nouns · Family", w:[
 {en:"Brother-in-law", tr:"Gis", he:"גִּיס", pl:"Gisim", plHe:"גִּיסִים",
  mn:"GEES — \"GEEZ, another in-law.\" Short and easy; add -a for the sister-in-law.",
  ex:["Ha-gis sheli bah la-arucha.","הַגִּיס שֶׁלִּי בָּא לָאֲרוּחָה.","My brother-in-law is coming to the meal."]},
 {en:"Sister-in-law", tr:"Gisa", he:"גִּיסָה", pl:"Gisot", plHe:"גִּיסוֹת",
  mn:"gee-SA — gis + the feminine -a. Hebrew is beautifully regular here.",
  ex:["Ha-gisa sheli adrichalit.","הַגִּיסָה שֶׁלִּי אַדְרִיכָלִית.","My sister-in-law is an architect."]},
 {en:"Daughter-in-law / bride", tr:"Kala", he:"כַּלָּה", pl:"Kalot", plHe:"כַּלּוֹת",
  mn:"ka-LA — the same word covers \"bride\" and \"daughter-in-law\". Kala sounds like \"call-ah\" — the one being called into the family.",
  ex:["Ha-kala lovehet simla levana.","הַכַּלָּה לוֹבֶשֶׁת שִׂמְלָה לְבָנָה.","The bride wears a white dress."]},
 {en:"Son-in-law / groom", tr:"Chatan", he:"חָתָן", pl:"Chatanim", plHe:"חֲתָנִים",
  mn:"cha-TAN — the groom at the chatuna (wedding). Same root: ch-t-n.",
  ex:["Ha-chatan ve-ha-kala rokdim.","הֶחָתָן וְהַכַּלָּה רוֹקְדִים.","The groom and bride are dancing."]},
 {en:"Step- (relative)", tr:"Choreg / Choreget", he:"חוֹרֵג / חוֹרֶגֶת", pl:"—", plHe:"—",
  mn:"cho-REG — literally \"deviating / outside the norm\". Add it after the relative: ach choreg = stepbrother.",
  ex:["Ha-ach ha-choreg sheli gar be-Amerika.","הָאָח הַחוֹרֵג שֶׁלִּי גָּר בְּאָמֶרִיקָה.","My stepbrother lives in America."]}]},

{t:"Nieces, nephews, grandchildren", c:"Nouns · Family", w:[
 {en:"Nephew", tr:"Achyan", he:"אַחְיָן", pl:"Achyanim", plHe:"אַחְיָנִים",
  mn:"ach-YAN — from ach (brother): your brother's kid. \"Brother-ian\".",
  ex:["Ha-achyan sheli ben chamesh.","הָאַחְיָן שֶׁלִּי בֶּן חָמֵשׁ.","My nephew is five years old."]},
 {en:"Niece", tr:"Achyanit", he:"אַחְיָנִית", pl:"Achyaniot", plHe:"אַחְיָנִיּוֹת",
  mn:"ach-ya-NEET — nephew + the feminine -it ending.",
  ex:["Ha-achyanit sheli lomedet balet.","הָאַחְיָנִית שֶׁלִּי לוֹמֶדֶת בָּלֶט.","My niece studies ballet."]},
 {en:"Grandson", tr:"Neched", he:"נֶכֶד", pl:"Nechadim", plHe:"נְכָדִים",
  mn:"NEH-ched — say \"NEXT generation\" — the neched is next in line.",
  ex:["Savta mefaneket et ha-neched.","סָבְתָא מְפַנֶּקֶת אֶת הַנֶּכֶד.","Grandma spoils her grandson."]},
 {en:"Granddaughter", tr:"Nechda", he:"נֶכְדָּה", pl:"Nechadot", plHe:"נְכָדוֹת",
  mn:"NECH-da — neched + the feminine -a.",
  ex:["Ha-nechda shelo bat shalosh.","הַנֶּכְדָּה שֶׁלּוֹ בַּת שָׁלוֹשׁ.","His granddaughter is three years old."]},
 {en:"Great-grandson", tr:"Nin", he:"נִין", pl:"Ninim", plHe:"נִינִים",
  mn:"NEEN — one generation further than neched, and one syllable shorter. Easy pair to remember together.",
  ex:["Yesh lo shlosha ninim.","יֵשׁ לוֹ שְׁלוֹשָׁה נִינִים.","He has three great-grandsons."]},
 {en:"Great-granddaughter", tr:"Nina", he:"נִינָה", pl:"Ninot", plHe:"נִינוֹת",
  mn:"nee-NA — nin + -a, exactly like neched/nechda.",
  ex:["Ha-nina shela nolda etmol.","הַנִּינָה שֶׁלָּהּ נוֹלְדָה אֶתְמוֹל.","Her great-granddaughter was born yesterday."]}]},

{t:"People around you", c:"Nouns · People", w:[
 {en:"Guest", tr:"Oreach / Orachat", he:"אוֹרֵחַ / אוֹרַחַת", pl:"Orchim / Orchot", plHe:"אוֹרְחִים / אוֹרְחוֹת",
  mn:"o-RE-ach — from orach (a way/path): a guest is someone traveling your way. Hachnasat orchim = hospitality.",
  ex:["Ha-orchim magi'im be-shesh.","הָאוֹרְחִים מַגִּיעִים בְּשֵׁשׁ.","The guests arrive at six."]},
 {en:"Pair / couple", tr:"Zug", he:"זוּג", pl:"Zugot", plHe:"זוּגוֹת",
  mn:"ZOOG — think \"ZOO-G\": animals boarded the ark two by two. Ben zug / bat zug = partner (male / female).",
  ex:["Kaniti zug garbayim chadash.","קָנִיתִי זוּג גַּרְבַּיִם חָדָשׁ.","I bought a new pair of socks."]},
 {en:"Immigrant (to Israel)", tr:"Oleh / Olah", he:"עוֹלֶה / עוֹלָה", pl:"Olim / Olot", plHe:"עוֹלִים / עוֹלוֹת",
  mn:"o-LEH — from la'alot, \"to go up\". Moving to Israel is aliyah — an ascent — so an immigrant is one who \"goes up\".",
  ex:["Ha-olim ha-chadashim lomdim ivrit be-ulpan.","הָעוֹלִים הַחֲדָשִׁים לוֹמְדִים עִבְרִית בְּאֻלְפָּן.","The new immigrants study Hebrew at an ulpan."]},
 {en:"Idiot / fool", tr:"Tembel / Tembelet", he:"טֶמְבֶּל / טֶמְבֶּלֶת", pl:"Tembelim / Tembelot", plHe:"טֶמְבְּלִים / טֶמְבְּלוֹת",
  mn:"TEM-bel — a TUMBLE-brain. The classic Israeli sun hat is even called a kova tembel, an \"idiot's hat\".",
  ex:["Al tihiye tembel, kach mitria.","אַל תִּהְיֶה טֶמְבֶּל, קַח מִטְרִיָּה.","Don't be an idiot, take an umbrella."]},
 {en:"Soldier", tr:"Chayal / Chayelet", he:"חַיָּל / חַיֶּלֶת", pl:"Chayalim / Chayalot", plHe:"חַיָּלִים / חַיָּלוֹת",
  mn:"cha-YAL — from chayil, \"strength/valor\". Eshet chayil = \"a woman of valor\".",
  ex:["Ha-chayelet chozeret ha-baita le-shabbat.","הַחַיֶּלֶת חוֹזֶרֶת הַבַּיְתָה לְשַׁבָּת.","The female soldier comes home for Shabbat."]}]}
];
