/* ===== NOUNS, part B — professions, clothing ===== */
const NOUNS_B = [
{t:"People who heal", c:"Nouns · Professions", w:[
 {en:"Doctor", tr:"Rofe / Rofa", he:"רוֹפֵא / רוֹפְאָה", pl:"Rofim / Rofot", plHe:"רוֹפְאִים / רוֹפְאוֹת",
  mn:"ro-FEH — think of a doctor who says \"ro-FEH, you'll be fine.\" Refua = medicine; refua shlema = \"get well soon\".",
  ex:["Ha-rofa bodeket et ha-choleh.","הָרוֹפְאָה בּוֹדֶקֶת אֶת הַחוֹלֶה.","The doctor examines the patient."]},
 {en:"Dentist", tr:"Rofe / Rofat shinayim", he:"רוֹפֵא / רוֹפְאַת שִׁנַּיִם", pl:"Rofei / Rofot shinayim", plHe:"רוֹפְאֵי / רוֹפְאוֹת שִׁנַּיִם",
  mn:"Literally \"teeth doctor\" — Hebrew builds compound jobs by stacking nouns. Shen (tooth) → shinayim.",
  ex:["Ani holech le-rofe shinayim pa'amayim ba-shana.","אֲנִי הוֹלֵךְ לְרוֹפֵא שִׁנַּיִם פַּעֲמַיִם בַּשָּׁנָה.","I go to the dentist twice a year."]},
 {en:"Psychologist", tr:"Psicholog / Psichologit", he:"פְּסִיכוֹלוֹג / פְּסִיכוֹלוֹגִית", pl:"Psichologim", plHe:"פְּסִיכוֹלוֹגִים",
  mn:"Straight from English — just add the -it for the feminine. Hebrew borrows freely for modern professions.",
  ex:["Hi psichologit le-yeladim.","הִיא פְּסִיכוֹלוֹגִית לִילָדִים.","She's a children's psychologist."]},
 {en:"Therapist / caregiver", tr:"Metapel / Metapelet", he:"מְטַפֵּל / מְטַפֶּלֶת", pl:"Metaplim / Metaplot", plHe:"מְטַפְּלִים / מְטַפְּלוֹת",
  mn:"me-ta-PEL — from letapel be-, \"to take care of\". A metapelet is also a nanny.",
  ex:["Ha-metapelet ba'a kol boker.","הַמְּטַפֶּלֶת בָּאָה כָּל בֹּקֶר.","The caregiver comes every morning."]},
 {en:"Social worker", tr:"Oved / Ovedet sotzialit", he:"עוֹבֵד / עוֹבֶדֶת סוֹצְיָאלִית", pl:"Ovdim / Ovdot sotzialiyot", plHe:"עוֹבְדִים / עוֹבְדוֹת סוֹצְיָאלִיּוֹת",
  mn:"oved = worker (from la'avod, to work) + sotzialit. Literally \"social worker\", word for word.",
  ex:["Ha-ovedet ha-sotzialit ozeret la-mishpacha.","הָעוֹבֶדֶת הַסּוֹצְיָאלִית עוֹזֶרֶת לַמִּשְׁפָּחָה.","The social worker helps the family."]}]},

{t:"Law and order", c:"Nouns · Professions", w:[
 {en:"Lawyer", tr:"Orech din / Orechet din", he:"עוֹרֵךְ דִּין / עוֹרֶכֶת דִּין", pl:"Orchei din / Orchot din", plHe:"עוֹרְכֵי דִּין / עוֹרְכוֹת דִּין",
  mn:"orech = editor/arranger, din = law. A lawyer is literally \"an arranger of the law\".",
  ex:["Ha-orechet din kor'et et ha-chozeh.","עוֹרֶכֶת הַדִּין קוֹרֵאת אֶת הַחוֹזֶה.","The lawyer reads the contract."]},
 {en:"Judge", tr:"Shofet / Shofetet", he:"שׁוֹפֵט / שׁוֹפֶטֶת", pl:"Shoftim", plHe:"שׁוֹפְטִים",
  mn:"sho-FET — the biblical Book of Judges is Shoftim. Also the referee in a soccer match.",
  ex:["Ha-shofet mekabel hachlata.","הַשּׁוֹפֵט מְקַבֵּל הַחְלָטָה.","The judge makes a decision."]},
 {en:"Police officer", tr:"Shoter / Shoteret", he:"שׁוֹטֵר / שׁוֹטֶרֶת", pl:"Shotrim", plHe:"שׁוֹטְרִים",
  mn:"sho-TER — a shoter will give you a TICKET. Mishtara = the police force.",
  ex:["Ha-shoter otzer et ha-mechonit.","הַשּׁוֹטֵר עוֹצֵר אֶת הַמְּכוֹנִית.","The police officer stops the car."]},
 {en:"Officer (military)", tr:"Katzin / Ktzina", he:"קָצִין / קְצִינָה", pl:"Katzinim / Ktzinot", plHe:"קָצִינִים / קְצִינוֹת",
  mn:"ka-TSEEN — an officer is KEEN and in command. One rung above the chayal.",
  ex:["Ha-katzin medaber im ha-chayalim.","הַקָּצִין מְדַבֵּר עִם הַחַיָּלִים.","The officer speaks with the soldiers."]},
 {en:"Guard / watchman", tr:"Shomer / Shomeret", he:"שׁוֹמֵר / שׁוֹמֶרֶת", pl:"Shomrim / Shomrot", plHe:"שׁוֹמְרִים / שׁוֹמְרוֹת",
  mn:"Exactly the verb lishmor turned into a person — Hebrew makes job titles this way constantly (kotev → writer, shomer → guard).",
  ex:["Ha-shomer omed lifnei ha-binyan.","הַשּׁוֹמֵר עוֹמֵד לִפְנֵי הַבִּנְיָן.","The guard stands in front of the building."]}]},

{t:"Building and serving", c:"Nouns · Professions", w:[
 {en:"Architect", tr:"Adrichal / Adrichalit", he:"אַדְרִיכָל / אַדְרִיכָלִית", pl:"Adrichalim / Adrichaliot", plHe:"אַדְרִיכָלִים / אַדְרִיכָלִיּוֹת",
  mn:"ad-ri-CHAL — a long, grand word for a person who designs grand things. Adrichalut = architecture.",
  ex:["Ha-adrichalit metzayeret et ha-binyan.","הָאַדְרִיכָלִית מְצַיֶּרֶת אֶת הַבִּנְיָן.","The architect draws the building."]},
 {en:"Engineer", tr:"Mehandes / Mehandeset", he:"מְהַנְדֵּס / מְהַנְדֶּסֶת", pl:"Mehandesim / Mehandesot", plHe:"מְהַנְדְּסִים / מְהַנְדְּסוֹת",
  mn:"me-han-DES — think \"my HANDS\" — the person who builds with precision. Handasa = engineering (and geometry).",
  ex:["Ha-mehandes oved al gesher chadash.","הַמְּהַנְדֵּס עוֹבֵד עַל גֶּשֶׁר חָדָשׁ.","The engineer works on a new bridge."]},
 {en:"Farmer", tr:"Chaklai / Chaklait", he:"חַקְלַאי / חַקְלָאִית", pl:"Chaklaim / Chaklaiot", plHe:"חַקְלָאִים / חַקְלָאִיּוֹת",
  mn:"chak-LAI — from chakla, an Aramaic word for field. Chakla'ut = agriculture, a proud Israeli word.",
  ex:["Ha-chaklai megadel agvaniot.","הַחַקְלַאי מְגַדֵּל עַגְבָנִיּוֹת.","The farmer grows tomatoes."]},
 {en:"Cook / chef", tr:"Tabach / Tabachit", he:"טַבָּח / טַבָּחִית", pl:"Tabachim", plHe:"טַבָּחִים",
  mn:"ta-BACH — a chef who cooks up a BATCH. Mitbach (kitchen) is the same root: t-b-ch.",
  ex:["Ha-tabach mevashel ba-mitbach.","הַטַּבָּח מְבַשֵּׁל בַּמִּטְבָּח.","The cook cooks in the kitchen."]},
 {en:"Waiter", tr:"Meltzar / Meltzarit", he:"מֶלְצַר / מֶלְצָרִית", pl:"Meltzarim", plHe:"מֶלְצָרִים",
  mn:"MEL-tsar — the waiter is the little \"TSAR\" of your table, bringing the MEAL.",
  ex:["Ha-meltzar mevi et ha-tafrit.","הַמֶּלְצַר מֵבִיא אֶת הַתַּפְרִיט.","The waiter brings the menu."]}]},

{t:"The arts", c:"Nouns · Professions", w:[
 {en:"Artist", tr:"Oman / Omanit", he:"אָמָּן / אָמָּנִית", pl:"Omanim / Omaniot", plHe:"אָמָּנִים / אָמָּנִיּוֹת",
  mn:"o-MAN — an artist is a craftsMAN. Omanut = art.",
  ex:["Ha-omanit motzet hashra'a ba-teva.","הָאָמָּנִית מוֹצֵאת הַשְׁרָאָה בַּטֶּבַע.","The artist finds inspiration in nature."]},
 {en:"Painter", tr:"Tzayar / Tzayeret", he:"צַיָּר / צַיֶּרֶת", pl:"Tzayarim / Tzayarot", plHe:"צַיָּרִים / צַיָּרוֹת",
  mn:"tsa-YAR — from tzeva (color) and tziur (a drawing). A tzayar makes tziurim.",
  ex:["Ha-tzayar mezayer tmuna gdola.","הַצַּיָּר מְצַיֵּר תְּמוּנָה גְּדוֹלָה.","The painter paints a big picture."]},
 {en:"Writer / author", tr:"Sofer / Soferet", he:"סוֹפֵר / סוֹפֶרֶת", pl:"Sofrim / Sofrot", plHe:"סוֹפְרִים / סוֹפְרוֹת",
  mn:"so-FER — same root as sefer (book) and sipur (story). A sofer is also the scribe who writes a Torah scroll.",
  ex:["Ha-soferet kotevet sefer chadash.","הַסּוֹפֶרֶת כּוֹתֶבֶת סֵפֶר חָדָשׁ.","The writer is writing a new book."]},
 {en:"Musician", tr:"Muzikai / Muzikait", he:"מוּזִיקַאי / מוּזִיקָאִית", pl:"Muzikaim / Muzikaiot", plHe:"מוּזִיקָאִים / מוּזִיקָאִיּוֹת",
  mn:"Borrowed word + the Hebrew -ai ending that marks a practitioner (chaklai, bamai, muzikai).",
  ex:["Ha-muzikai menagen kol erev ba-bar.","הַמּוּזִיקַאי מְנַגֵּן כָּל עֶרֶב בַּבָּר.","The musician plays every evening at the bar."]},
 {en:"Director (film / theatre)", tr:"Bamai / Bamait", he:"בַּמַּאי / בַּמָּאִית", pl:"Bamaim / Bamaiyot", plHe:"בַּמָּאִים / בַּמָּאִיּוֹת",
  mn:"ba-MAI — from bama, \"a stage\". The bamai is the one who runs the stage.",
  ex:["Ha-bamai mesaber la-sachkanim ma laasot.","הַבַּמַּאי מַסְבִּיר לַשַּׂחְקָנִים מָה לַעֲשׂוֹת.","The director explains to the actors what to do."]}]},

{t:"Music, modeling, driving", c:"Nouns · Professions", w:[
 {en:"Pianist", tr:"Psantran / Psantranit", he:"פְּסַנְתְּרָן / פְּסַנְתְּרָנִית", pl:"Psantranim / Psantraniyot", plHe:"פְּסַנְתְּרָנִים / פְּסַנְתְּרָנִיּוֹת",
  mn:"psan-TRAN — from psanter (piano) + the -an ending for a doer. Same pattern as kanar (violinist).",
  ex:["Ha-psantranit menagenet be-kontzert.","הַפְּסַנְתְּרָנִית מְנַגֶּנֶת בְּקוֹנְצֶרְט.","The pianist plays in a concert."]},
 {en:"Violinist", tr:"Kanar / Kanarit", he:"כַּנָּר / כַּנָּרִית", pl:"Kanarim / Kanariyot", plHe:"כַּנָּרִים / כַּנָּרִיּוֹת",
  mn:"ka-NAR — from kinor, the violin (and King David's harp was a kinor). \"Fiddler on the Roof\" is Kanar al ha-Gag.",
  ex:["Ha-kanar menagen be-tizmoret.","הַכַּנָּר מְנַגֵּן בְּתִזְמֹרֶת.","The violinist plays in an orchestra."]},
 {en:"Model", tr:"Dugman / Dugmanit", he:"דֻּגְמָן / דֻּגְמָנִית", pl:"Dugmanim / Dugmaniyot", plHe:"דֻּגְמָנִים / דֻּגְמָנִיּוֹת",
  mn:"dug-MAN — from dugma, \"an example\". A model is literally a walking example.",
  ex:["Ha-dugmanit lovehet begadim chadashim.","הַדֻּגְמָנִית לוֹבֶשֶׁת בְּגָדִים חֲדָשִׁים.","The model wears new clothes."]},
 {en:"Winner / conductor", tr:"Menatzeach / Menatzachat", he:"מְנַצֵּחַ / מְנַצַּחַת", pl:"Menatzchim / Menatzchot", plHe:"מְנַצְּחִים / מְנַצְּחוֹת",
  mn:"me-na-TSE-ach — nitzachon = victory. The orchestra conductor \"conquers\" the music — same word for both.",
  ex:["Ha-menatzeach al ha-tizmoret me'ule.","הַמְּנַצֵּחַ עַל הַתִּזְמֹרֶת מְעוּלֶה.","The conductor of the orchestra is excellent."]},
 {en:"Driver", tr:"Nahag / Nahaget", he:"נַהָג / נַהֶגֶת", pl:"Nahagim", plHe:"נַהָגִים",
  mn:"na-HAG — from linhog, to drive. \"Na-HAG\" — he HUGS the wheel.",
  ex:["Ha-nahag shel ha-otobus nechmad.","הַנַּהָג שֶׁל הָאוֹטוֹבּוּס נֶחְמָד.","The bus driver is nice."]}]},

{t:"Working life", c:"Nouns · Work", w:[
 {en:"Profession / subject", tr:"Miktzoa", he:"מִקְצוֹעַ", pl:"Miktzo-ot", plHe:"מִקְצוֹעוֹת",
  mn:"mik-TSO-a — your profession is your \"slice\" of the world (from ketza, an edge/section). Also a school subject.",
  ex:["Ma ha-miktzoa shelach?","מָה הַמִּקְצוֹעַ שֶׁלָּךְ?","What's your profession?"]},
 {en:"Internship / specialization", tr:"Hitmachut", he:"הִתְמַחוּת", pl:"Hitmachuyot", plHe:"הִתְמַחֻיּוֹת",
  mn:"hit-ma-CHOOT — from mumche, an expert. The hit- start means it's something you do to yourself: you make yourself an expert.",
  ex:["Ha-hitmachut shelo ba-beit cholim.","הַהִתְמַחוּת שֶׁלּוֹ בְּבֵית חוֹלִים.","His internship is at a hospital."]},
 {en:"Team / staff", tr:"Tzevet", he:"צֶוֶת", pl:"Tzvatim", plHe:"צְוָתִים",
  mn:"TSEH-vet — a tight crew. Related to tzav, an order/command — a team under orders.",
  ex:["Ha-tzevet oved yachad kol yom.","הַצֶּוֶת עוֹבֵד יַחַד כָּל יוֹם.","The team works together every day."]},
 {en:"Volunteer", tr:"Mitnadev / Mitnadevet", he:"מִתְנַדֵּב / מִתְנַדֶּבֶת", pl:"Mitnadvim / Mitnadvot", plHe:"מִתְנַדְּבִים / מִתְנַדְּבוֹת",
  mn:"mit-na-DEV — from nedava, a donation. The mit- prefix again: you give of yourself.",
  ex:["Ha-mitnadvim ozrim ba-kehila.","הַמִּתְנַדְּבִים עוֹזְרִים בַּקְּהִלָּה.","The volunteers help in the community."]},
 {en:"Secretary", tr:"Mazkir / Mazkira", he:"מַזְכִּיר / מַזְכִּירָה", pl:"Mazkirim / Mazkirot", plHe:"מַזְכִּירִים / מַזְכִּירוֹת",
  mn:"maz-KEER — from lizkor (to remember): the secretary is the one who makes you remember. Same root: z-k-r.",
  ex:["Ha-mazkira koveaat et ha-pgishot.","הַמַּזְכִּירָה קוֹבַעַת אֶת הַפְּגִישׁוֹת.","The secretary schedules the meetings."]}]},

{t:"Everyday clothes", c:"Nouns · Clothing", w:[
 {en:"Clothing / a garment", tr:"Beged", he:"בֶּגֶד", pl:"Begadim", plHe:"בְּגָדִים",
  mn:"BEH-ged — you wear a BAGGED item. Usually used in the plural: begadim = clothes.",
  ex:["Ani mesaderet et ha-begadim ba-aron.","אֲנִי מְסַדֶּרֶת אֶת הַבְּגָדִים בָּאָרוֹן.","I'm arranging the clothes in the closet."]},
 {en:"Shirt / blouse", tr:"Chultza", he:"חֻלְצָה", pl:"Chultzot", plHe:"חֻלְצוֹת",
  mn:"chul-TSA — sounds like \"HOLD-za\" — the thing that holds your torso.",
  ex:["Ha-chultza ha-levana meluchlechet.","הַחֻלְצָה הַלְּבָנָה מְלוּכְלֶכֶת.","The white shirt is dirty."]},
 {en:"Pants / trousers", tr:"Michnasayim", he:"מִכְנָסַיִם", pl:"— (always dual)", plHe:"—",
  mn:"mich-na-SA-yim — from lehachnis, \"to put in\": pants are what you put your legs INTO. Always dual, like all leg-and-eye words.",
  ex:["Ha-michnasayim ha-eleh ktzarim mid'i.","הַמִּכְנָסַיִם הָאֵלֶּה קְצָרִים מִדַּי.","These pants are too short."]},
 {en:"Dress", tr:"Simla", he:"שִׂמְלָה", pl:"Simlot", plHe:"שִׂמְלוֹת",
  mn:"sim-LA — a dress makes you SMILE-ah. Handy near sameach (happy).",
  ex:["Hi konah simla la-chatuna.","הִיא קוֹנָה שִׂמְלָה לַחֲתוּנָה.","She's buying a dress for the wedding."]},
 {en:"Skirt", tr:"Chatzait", he:"חֲצָאִית", pl:"Chatzaiyot", plHe:"חֲצָאִיּוֹת",
  mn:"cha-tsa-EET — from chetzi, \"half\": a skirt is half a dress. Perfectly logical.",
  ex:["Ha-chatzait aruka ve-tzivonit.","הַחֲצָאִית אֲרֻכָּה וְצִבְעוֹנִית.","The skirt is long and colorful."]}]},

{t:"Dressing up", c:"Nouns · Clothing", w:[
 {en:"Coat", tr:"Me-il", he:"מְעִיל", pl:"Me-ilim", plHe:"מְעִילִים",
  mn:"meh-EEL — a coat SEALS you in against the cold. \"Me-SEAL.\"",
  ex:["Kach me'il, kar ba-chutz.","קַח מְעִיל, קַר בַּחוּץ.","Take a coat, it's cold outside."]},
 {en:"Suit", tr:"Chalifa", he:"חֲלִיפָה", pl:"Chalifot", plHe:"חֲלִיפוֹת",
  mn:"cha-lee-FA — from lehachlif, \"to change/swap\": a suit is your change of clothes for special occasions.",
  ex:["Hu lovesh chalifa shchora la-avoda.","הוּא לוֹבֵשׁ חֲלִיפָה שְׁחוֹרָה לָעֲבוֹדָה.","He wears a black suit to work."]},
 {en:"Tie", tr:"Aniva", he:"עֲנִיבָה", pl:"Anivot", plHe:"עֲנִיבוֹת",
  mn:"a-nee-VA — from la'anov, to knot. A tie is \"the knotted thing\".",
  ex:["Ha-aniva shelo tzivonit mid'i.","הָעֲנִיבָה שֶׁלּוֹ צִבְעוֹנִית מִדַּי.","His tie is too colorful."]},
 {en:"Belt", tr:"Chagora", he:"חֲגוֹרָה", pl:"Chagorot", plHe:"חֲגוֹרוֹת",
  mn:"cha-go-RA — a belt HUGS you around. Chagorat betichut = a seatbelt.",
  ex:["Tachgor chagorat betichut ba-mechonit.","תַּחְגֹּר חֲגוֹרַת בְּטִיחוּת בַּמְּכוֹנִית.","Fasten your seatbelt in the car."]},
 {en:"Pocket", tr:"Kis", he:"כִּיס", pl:"Kisim", plHe:"כִּיסִים",
  mn:"KEES — you KEEP things in it. Kis also means a bag or a pouch.",
  ex:["Ha-mafteach ba-kis shel ha-michnasayim.","הַמַּפְתֵּחַ בַּכִּיס שֶׁל הַמִּכְנָסַיִם.","The key is in the pants pocket."]}]},

{t:"On your feet and hands", c:"Nouns · Clothing", w:[
 {en:"Shoe", tr:"Na'al", he:"נַעַל", pl:"Na'alayim", plHe:"נְעָלַיִם",
  mn:"NA-al — same root as lin'ol, the verb for wearing shoes. Dual ending because shoes come in twos.",
  ex:["Ha-na'alayim ha-chadashot lo nochot.","הַנַּעֲלַיִם הַחֲדָשׁוֹת לֹא נוֹחוֹת.","The new shoes aren't comfortable."]},
 {en:"Boot", tr:"Magaf", he:"מַגָּף", pl:"Magafayim", plHe:"מַגָּפַיִם",
  mn:"ma-GAF — a boot with a big GAFF/cuff at the top.",
  ex:["Ba-choref ani no'elet magafayim.","בַּחֹרֶף אֲנִי נוֹעֶלֶת מַגָּפַיִם.","In winter I wear boots."]},
 {en:"Sock", tr:"Gerev", he:"גֶּרֶב", pl:"Garbayim", plHe:"גַּרְבַּיִם",
  mn:"GEH-rev — sounds like \"GRAB\" — grab a pair of socks.",
  ex:["Ei-ze garbayim nekiyim yesh?","אֵילוּ גַּרְבַּיִם נְקִיִּים יֵשׁ?","Which clean socks are there?"]},
 {en:"Slippers", tr:"Na'alei bayit", he:"נַעֲלֵי בַּיִת", pl:"Na'alei bayit", plHe:"נַעֲלֵי בַּיִת",
  mn:"Literally \"house shoes\" — na'alayim + bayit. Hebrew loves these transparent compounds.",
  ex:["Ani noel na'alei bayit ba-erev.","אֲנִי נוֹעֵל נַעֲלֵי בַּיִת בָּעֶרֶב.","I wear slippers in the evening."]},
 {en:"Glove", tr:"Kfafa", he:"כְּפָפָה", pl:"Kfafot", plHe:"כְּפָפוֹת",
  mn:"kfa-FA — from kaf, the palm of the hand. A glove is \"the palm-thing\".",
  ex:["Tzarich kfafot kshe-kar me'od.","צָרִיךְ כְּפָפוֹת כְּשֶׁקַּר מְאוֹד.","You need gloves when it's very cold."]}]},

{t:"Head and shoulders", c:"Nouns · Clothing", w:[
 {en:"Hat", tr:"Kova", he:"כּוֹבַע", pl:"Kova'im", plHe:"כּוֹבָעִים",
  mn:"KO-va — a hat COVERS you. Ko-va / co-ver: close enough to stick.",
  ex:["Tasim kova, ha-shemesh chazaka.","תָּשִׂים כּוֹבַע, הַשֶּׁמֶשׁ חֲזָקָה.","Put on a hat, the sun is strong."]},
 {en:"Scarf", tr:"Tza'if", he:"צָעִיף", pl:"Tze'ifim", plHe:"צְעִיפִים",
  mn:"tsa-EEF — it wraps you and you feel SAFE. (Careful: tza'ir = young, one letter apart.)",
  ex:["Ha-tza'if ha-adom mit'im la-me'il.","הַצָּעִיף הָאָדֹם מַתְאִים לַמְּעִיל.","The red scarf matches the coat."]},
 {en:"Glasses (to see)", tr:"Mishkafayim", he:"מִשְׁקָפַיִם", pl:"— (always dual)", plHe:"—",
  mn:"mish-ka-FA-yim — from lehashkif, \"to look out\". Two lenses, so the -ayim dual ending.",
  ex:["Ani lo ro'eh klum bli mishkafayim.","אֲנִי לֹא רוֹאֶה כְּלוּם בְּלִי מִשְׁקָפַיִם.","I can't see anything without glasses."]},
 {en:"Sunglasses", tr:"Mishkefei shemesh", he:"מִשְׁקְפֵי שֶׁמֶשׁ", pl:"— (always dual)", plHe:"—",
  mn:"Glasses + shemesh (sun). Compound again: \"glasses of sun\".",
  ex:["Shachachti et mishkefei ha-shemesh ba-mechonit.","שָׁכַחְתִּי אֶת מִשְׁקְפֵי הַשֶּׁמֶשׁ בַּמְּכוֹנִית.","I forgot my sunglasses in the car."]},
 {en:"Backpack / schoolbag", tr:"Yalkut", he:"יַלְקוּט", pl:"Yalkutim", plHe:"יַלְקוּטִים",
  mn:"yal-KOOT — a YELLOW KIT on your back. Every Israeli schoolkid carries one.",
  ex:["Ha-yalkut shel ha-yeled kaved me'od.","הַיַּלְקוּט שֶׁל הַיֶּלֶד כָּבֵד מְאוֹד.","The child's backpack is very heavy."]}]},

{t:"Jewelry and accessories", c:"Nouns · Clothing", w:[
 {en:"Jewelry / an ornament", tr:"Tachshit", he:"תַּכְשִׁיט", pl:"Tachshitim", plHe:"תַּכְשִׁיטִים",
  mn:"tach-SHEET — a fancy sheet of metal. Slang bonus: calling a kid a tachshit means \"you little piece of work\".",
  ex:["Hi konah tachshitim ba-shuk.","הִיא קוֹנָה תַּכְשִׁיטִים בַּשּׁוּק.","She buys jewelry at the market."]},
 {en:"Ring", tr:"Taba'at", he:"טַבַּעַת", pl:"Taba'ot", plHe:"טַבָּעוֹת",
  mn:"ta-BA-at — from tova (to sink/stamp) — a signet ring stamps a seal. The Lord of the Rings is Sar Ha-Taba'ot.",
  ex:["Ha-taba'at shela me-zahav.","הַטַּבַּעַת שֶׁלָּהּ מִזָּהָב.","Her ring is made of gold."]},
 {en:"Bracelet", tr:"Tzamid", he:"צָמִיד", pl:"Tzmidim", plHe:"צְמִידִים",
  mn:"tsa-MEED — from tzamud, \"attached/stuck to\". A bracelet stays attached to your wrist.",
  ex:["Kibalti tzamid yafe le-yom huledet.","קִבַּלְתִּי צָמִיד יָפֶה לְיוֹם הֻלֶּדֶת.","I got a beautiful bracelet for my birthday."]},
 {en:"Necklace / chain", tr:"Sharsheret", he:"שַׁרְשֶׁרֶת", pl:"Sharsharot", plHe:"שַׁרְשָׁרוֹת",
  mn:"shar-SHEH-ret — say it fast and it rattles like links: shar-sheh-ret.",
  ex:["Ha-sharsheret ha-zo atika.","הַשַּׁרְשֶׁרֶת הַזֹּאת עַתִּיקָה.","This necklace is ancient."]},
 {en:"Watch / clock", tr:"Shaon", he:"שָׁעוֹן", pl:"Shaonim", plHe:"שְׁעוֹנִים",
  mn:"sha-ON — from sha'a (hour). A watch is \"the hour-thing\".",
  ex:["Ha-shaon sheli me'achar be-chamesh dakot.","הַשָּׁעוֹן שֶׁלִּי מְאַחֵר בְּחָמֵשׁ דַּקּוֹת.","My watch is five minutes slow."]},
 {en:"Costume", tr:"Tachposet", he:"תַּחְפֹּשֶׂת", pl:"Tachposot", plHe:"תַּחְפֹּשׂוֹת",
  mn:"tach-PO-set — from lechapes (to search) — a costume makes people search for who you really are. Purim is the tachposet holiday.",
  ex:["Ha-yeladim lovshim tachposot be-Purim.","הַיְּלָדִים לוֹבְשִׁים תַּחְפֹּשׂוֹת בְּפוּרִים.","The children wear costumes on Purim."]}]}
];
