/* ===== NOUNS, part C — home, household objects, food ===== */
const NOUNS_C = [
{t:"Where you live", c:"Nouns · Home", w:[
 {en:"Apartment", tr:"Dira", he:"דִּירָה", pl:"Dirot", plHe:"דִּירוֹת",
  mn:"dee-RA — you get a DEAL on a DIRA. Most Israelis live in one, so you'll hear it constantly.",
  ex:["Anachnu mechapsim dira gdola yoter.","אֲנַחְנוּ מְחַפְּשִׂים דִּירָה גְּדוֹלָה יוֹתֵר.","We're looking for a bigger apartment."]},
 {en:"Building", tr:"Binyan", he:"בִּנְיָן", pl:"Binyanim", plHe:"בִּנְיָנִים",
  mn:"bin-YAN — from livnot (to build). Bonus: the seven Hebrew verb patterns are also called binyanim, \"buildings\".",
  ex:["Ha-binyan ha-ze atik me'od.","הַבִּנְיָן הַזֶּה עַתִּיק מְאוֹד.","This building is very old."]},
 {en:"Room", tr:"Cheder", he:"חֶדֶר", pl:"Chadarim", plHe:"חֲדָרִים",
  mn:"CHEH-der — the Jewish one-room schoolhouse was called a cheder. Note the vowel flip in the plural: cheder → chadarim.",
  ex:["Ba-dira yesh shlosha chadarim.","בַּדִּירָה יֵשׁ שְׁלוֹשָׁה חֲדָרִים.","There are three rooms in the apartment."]},
 {en:"Roof", tr:"Gag", he:"גַּג", pl:"Gagot", plHe:"גַּגּוֹת",
  mn:"GAG — two letters, shaped like a little roof: ג is even pointy on top.",
  ex:["Anachnu yoshvim al ha-gag ba-erev.","אֲנַחְנוּ יוֹשְׁבִים עַל הַגַּג בָּעֶרֶב.","We sit on the roof in the evening."]},
 {en:"Garden / park / kindergarten", tr:"Gan", he:"גַּן", pl:"Ganim", plHe:"גַּנִּים",
  mn:"GAN — Gan Eden = the Garden of Eden. A kindergarten is a gan yeladim, \"children's garden\".",
  ex:["Ha-yeladim mesachakim ba-gan.","הַיְּלָדִים מְשַׂחֲקִים בַּגַּן.","The children play in the park."]}]},

{t:"Rooms of the house", c:"Nouns · Home", w:[
 {en:"Bedroom", tr:"Chadar sheina", he:"חֶדֶר שֵׁנָה", pl:"Chadrei sheina", plHe:"חַדְרֵי שֵׁנָה",
  mn:"cheder + sheina (sleep). \"Room of sleep.\" Notice how cheder becomes chadar when it's glued to another noun.",
  ex:["Chadar ha-sheina shaket ve-nachim.","חֲדַר הַשֵּׁנָה שָׁקֵט וְנָעִים.","The bedroom is quiet and pleasant."]},
 {en:"Living room", tr:"Salon", he:"סָלוֹן", pl:"Salonim", plHe:"סָלוֹנִים",
  mn:"sa-LON — straight from the French \"salon\". A freebie.",
  ex:["Ha-mishpacha tzofa be-televizia ba-salon.","הַמִּשְׁפָּחָה צוֹפָה בַּטֶּלֶוִיזְיָה בַּסָּלוֹן.","The family watches TV in the living room."]},
 {en:"Dining room", tr:"Chadar ochel", he:"חֶדֶר אוֹכֶל", pl:"Chadrei ochel", plHe:"חַדְרֵי אוֹכֶל",
  mn:"\"Room of food\" — ochel is both \"eats\" and \"food\". On a kibbutz the chadar ochel is the communal dining hall.",
  ex:["Anachnu ochlim be-chadar ha-ochel be-shabbat.","אֲנַחְנוּ אוֹכְלִים בַּחֲדַר הָאֹכֶל בְּשַׁבָּת.","We eat in the dining room on Shabbat."]},
 {en:"Kitchen", tr:"Mitbach", he:"מִטְבָּח", pl:"Mitbachim", plHe:"מִטְבָּחִים",
  mn:"mit-BACH — from tabach (cook). The ma-/mi- prefix marks a PLACE where something happens: mitbach = place of cooking.",
  ex:["Ha-mitbach katan aval nochi.","הַמִּטְבָּח קָטָן אֲבָל נוֹחַ.","The kitchen is small but comfortable."]},
 {en:"Furniture", tr:"Rahit", he:"רָהִיט", pl:"Rahitim", plHe:"רְהִיטִים",
  mn:"ra-HEET — a piece of furniture you'd HEAT your feet by. Usually plural: rahitim.",
  ex:["Kaninu rahitim chadashim la-salon.","קָנִינוּ רְהִיטִים חֲדָשִׁים לַסָּלוֹן.","We bought new furniture for the living room."]}]},

{t:"Around the house", c:"Nouns · Home", w:[
 {en:"Door", tr:"Delet", he:"דֶּלֶת", pl:"Dlatot", plHe:"דְּלָתוֹת",
  mn:"DEH-let — the door LETS you in: de-LET. Also the Hebrew letter ד, dalet.",
  ex:["Ha-delet sgura, tidfok bevakasha.","הַדֶּלֶת סְגוּרָה, תִּדְפֹּק בְּבַקָּשָׁה.","The door is closed, please knock."]},
 {en:"Window", tr:"Chalon", he:"חַלּוֹן", pl:"Chalonot", plHe:"חַלּוֹנוֹת",
  mn:"cha-LON — you stare out the window for a LONG time.",
  ex:["Tiftach et ha-chalon, cham po.","תִּפְתַּח אֶת הַחַלּוֹן, חַם פֹּה.","Open the window, it's hot here."]},
 {en:"Closet / cupboard", tr:"Aron", he:"אָרוֹן", pl:"Aronot", plHe:"אֲרוֹנוֹת",
  mn:"a-RON — the Ark of the Covenant is the Aron ha-Brit, and the Torah cabinet in a synagogue is the aron kodesh. It's a big box.",
  ex:["Ha-begadim ba-aron sheli.","הַבְּגָדִים בָּאָרוֹן שֶׁלִּי.","The clothes are in my closet."]},
 {en:"Curtain", tr:"Vilon", he:"וִילוֹן", pl:"Vilonot", plHe:"וִילוֹנוֹת",
  mn:"vee-LON — a VEIL that's LONG. Borrowed from the same European root as \"voile\".",
  ex:["Ha-vilonot chadashim ve-tzivoniim.","הַוִּילוֹנוֹת חֲדָשִׁים וְצִבְעוֹנִיִּים.","The curtains are new and colorful."]},
 {en:"Bed", tr:"Mita", he:"מִטָּה", pl:"Mitot", plHe:"מִטּוֹת",
  mn:"mee-TA — a bed is roughly a METER wide. (Don't confuse with mata = downward.)",
  ex:["Ha-chatul yashen al ha-mita sheli.","הֶחָתוּל יָשֵׁן עַל הַמִּטָּה שֶׁלִּי.","The cat sleeps on my bed."]},
 {en:"Refrigerator", tr:"Mekarer", he:"מְקָרֵר", pl:"Mekarerim", plHe:"מְקָרְרִים",
  mn:"me-ka-RER — from kar (cold). The mekarer is \"the cold-maker\".",
  ex:["Yesh chalav ba-mekarer?","יֵשׁ חָלָב בַּמְּקָרֵר?","Is there milk in the fridge?"]}]},

{t:"Everyday objects", c:"Nouns · Household", w:[
 {en:"Key", tr:"Mafteach", he:"מַפְתֵּחַ", pl:"Maftechot", plHe:"מַפְתְּחוֹת",
  mn:"maf-TE-ach — from lifto'ach (to open). The ma- prefix marks a TOOL: a key is \"the opening-tool\".",
  ex:["Ibadeti et ha-mafteach shel ha-bayit.","אִבַּדְתִּי אֶת הַמַּפְתֵּחַ שֶׁל הַבַּיִת.","I lost the house key."]},
 {en:"Soap", tr:"Sabon", he:"סַבּוֹן", pl:"Sabonim", plHe:"סַבּוֹנִים",
  mn:"sa-BON — practically the English \"soap\" with a Spanish accent (jabón). Free word.",
  ex:["Nigmar ha-sabon ba-miklachat.","נִגְמַר הַסַּבּוֹן בַּמִּקְלַחַת.","The soap ran out in the shower."]},
 {en:"Towel", tr:"Magevet", he:"מַגֶּבֶת", pl:"Magavot", plHe:"מַגָּבוֹת",
  mn:"ma-GEH-vet — from lenagev, \"to wipe dry\". Again the ma- tool-prefix: the drying-tool.",
  ex:["Tavi li magevet nekiya, bevakasha.","תָּבִיא לִי מַגֶּבֶת נְקִיָּה, בְּבַקָּשָׁה.","Bring me a clean towel, please."]},
 {en:"Toilet paper", tr:"Niyar toalet", he:"נְיָר טוֹאָלֵט", pl:"—", plHe:"—",
  mn:"niyar = paper (think \"NEAR\" — always keep it near). Then the borrowed \"toalet\".",
  ex:["Tzarich liknot niyar toalet.","צָרִיךְ לִקְנוֹת נְיָר טוֹאָלֵט.","We need to buy toilet paper."]},
 {en:"Trash / garbage", tr:"Zevel", he:"זֶבֶל", pl:"—", plHe:"—",
  mn:"ZEH-vel — originally \"manure\". Israelis use it for garbage and, in slang, for anything terrible: \"Ha-seret haya zevel.\"",
  ex:["Tizrok et ha-zevel, bevakasha.","תִּזְרֹק אֶת הַזֶּבֶל, בְּבַקָּשָׁה.","Throw out the trash, please."]}]},

{t:"At the table", c:"Nouns · Household", w:[
 {en:"Pot", tr:"Sir", he:"סִיר", pl:"Sirim", plHe:"סִירִים",
  mn:"SEER — you STIR the SIR. (Careful: sir = pot, shir = song.)",
  ex:["Ha-sir al ha-esh kvar chatzi sha'a.","הַסִּיר עַל הָאֵשׁ כְּבָר חֲצִי שָׁעָה.","The pot has been on the fire for half an hour."]},
 {en:"Bowl", tr:"Ke'ara", he:"קְעָרָה", pl:"Ke'arot", plHe:"קְעָרוֹת",
  mn:"ke-a-RA — a bowl is CURVED — \"ke-CURVE-ah\".",
  ex:["Sim et ha-salat ba-ke'ara ha-gdola.","שִׂים אֶת הַסָּלָט בַּקְּעָרָה הַגְּדוֹלָה.","Put the salad in the big bowl."]},
 {en:"Cup / glass", tr:"Kos", he:"כּוֹס", pl:"Kosot", plHe:"כּוֹסוֹת",
  mn:"KOS — at a wedding the groom breaks a kos. Sounds like \"cause\" — a cause for celebration.",
  ex:["Ani rotza kos mayim krerim.","אֲנִי רוֹצָה כּוֹס מַיִם קָרִים.","I want a glass of cold water."]},
 {en:"Napkin", tr:"Mapit", he:"מַפִּית", pl:"Mapiyot", plHe:"מַפִּיּוֹת",
  mn:"ma-PEET — from mapa (tablecloth) + the diminutive -it. A napkin is a \"little tablecloth\".",
  ex:["Tavi mapiyot la-shulchan.","תָּבִיא מַפִּיּוֹת לַשֻּׁלְחָן.","Bring napkins to the table."]},
 {en:"Silverware / cutlery", tr:"Sakum", he:"סַכּוּ״ם", pl:"—", plHe:"—",
  mn:"sa-KOOM — an acronym! Sakin (knife) + Kaf (spoon) + Mazleg (fork). The quotation marks tell you it's built from initials.",
  ex:["Ha-sakum ba-magera ha-rishona.","הַסַּכּוּ\"ם בַּמְּגֵרָה הָרִאשׁוֹנָה.","The silverware is in the first drawer."]},
 {en:"Spoon (large)", tr:"Kaf", he:"כַּף", pl:"Kapot", plHe:"כַּפּוֹת",
  mn:"KAF — the same word as the palm of your hand: both are little scoops. In recipes, kaf = tablespoon.",
  ex:["Hosif kaf shemen la-sir.","הוֹסֵף כַּף שֶׁמֶן לַסִּיר.","Add a tablespoon of oil to the pot."]},
 {en:"Spoon (small) / teaspoon", tr:"Kapit", he:"כַּפִּית", pl:"Kapiot", plHe:"כַּפִּיּוֹת",
  mn:"ka-PEET — kaf + the -it diminutive again, exactly like mapa → mapit. Hebrew shrinks things with -it.",
  ex:["Kapit sukar ba-kafe, bevakasha.","כַּפִּית סֻכָּר בַּקָּפֶה, בְּבַקָּשָׁה.","A teaspoon of sugar in the coffee, please."]}]},

{t:"Vegetables", c:"Nouns · Food", w:[
 {en:"Vegetable", tr:"Yerek", he:"יֶרֶק", pl:"Yerakot", plHe:"יְרָקוֹת",
  mn:"YEH-rek — from yarok, \"green\". Vegetables are \"the green things\".",
  ex:["Ani ochelet harbeh yerakot.","אֲנִי אוֹכֶלֶת הַרְבֵּה יְרָקוֹת.","I eat a lot of vegetables."]},
 {en:"Tomato", tr:"Agvania", he:"עַגְבָנִיָּה", pl:"Agvaniyot", plHe:"עַגְבָנִיּוֹת",
  mn:"ag-va-nee-YA — from agavim, \"love/passion\" — the tomato was once called the \"love apple\", exactly like the French pomme d'amour.",
  ex:["Ha-salat me-agvaniyot ve-melafefonim.","הַסָּלָט מֵעַגְבָנִיּוֹת וּמְלָפְפוֹנִים.","The salad is made of tomatoes and cucumbers."]},
 {en:"Onion", tr:"Batzal", he:"בָּצָל", pl:"Betzalim", plHe:"בְּצָלִים",
  mn:"ba-TSAL — cutting one makes you BAWL. Batzal ha-yarok = a green onion.",
  ex:["Ani chotech batzal la-marak.","אֲנִי חוֹתֵךְ בָּצָל לַמָּרָק.","I'm cutting an onion for the soup."]},
 {en:"Carrot", tr:"Gezer", he:"גֶּזֶר", pl:"Gzarim", plHe:"גְּזָרִים",
  mn:"GEH-zer — from ligzor, \"to cut\": a carrot is \"the cut-up thing\". Also, gezer sounds like \"geezer\" — a carrot with a nose.",
  ex:["Ha-shafan ohev gezer.","הַשָּׁפָן אוֹהֵב גֶּזֶר.","The rabbit likes carrots."]},
 {en:"Potato", tr:"Tapuach adama", he:"תַּפּוּחַ אֲדָמָה", pl:"Tapuchei adama", plHe:"תַּפּוּחֵי אֲדָמָה",
  mn:"Literally \"apple of the earth\" — exactly like the French pomme de terre. Adama = earth/soil.",
  ex:["Ani ofa tapuchei adama ba-tanur.","אֲנִי אוֹפָה תַּפּוּחֵי אֲדָמָה בַּתַּנּוּר.","I'm baking potatoes in the oven."]}]},

{t:"More from the kitchen", c:"Nouns · Food", w:[
 {en:"Cauliflower / cabbage", tr:"Kruv", he:"כְּרוּב", pl:"Kruvim", plHe:"כְּרוּבִים",
  mn:"KROOV — same spelling as keruv, an angel (cherub). A cauliflower does look a bit like a cloud of little cherubs.",
  ex:["Anachnu ofim kruv im shemen zayit.","אֲנַחְנוּ אוֹפִים כְּרוּב עִם שֶׁמֶן זַיִת.","We're roasting cauliflower with olive oil."]},
 {en:"Mushroom", tr:"Pitria", he:"פִּטְרִיָּה", pl:"Pitriyot", plHe:"פִּטְרִיּוֹת",
  mn:"pit-ree-YA — sounds like \"pizzeria\" — and mushrooms go on pizza.",
  ex:["Ha-pitriyot ba-rotev tze'imot.","הַפִּטְרִיּוֹת בָּרוֹטֶב טְעִימוֹת.","The mushrooms in the sauce are tasty."]},
 {en:"Olive", tr:"Zayit", he:"זַיִת", pl:"Zeytim", plHe:"זֵיתִים",
  mn:"ZA-yit — the Mount of Olives is Har ha-Zeitim. Shemen zayit = olive oil.",
  ex:["Yesh zeytim shchorim ba-salat.","יֵשׁ זֵיתִים שְׁחוֹרִים בַּסָּלָט.","There are black olives in the salad."]},
 {en:"Salt", tr:"Melach", he:"מֶלַח", pl:"—", plHe:"—",
  mn:"MEH-lach — the Dead Sea is Yam ha-Melach, \"the Sea of Salt\". Cousin of the English \"mineral\" family via Semitic m-l-ch.",
  ex:["Chaser melach ba-marak.","חָסֵר מֶלַח בַּמָּרָק.","The soup needs salt."]},
 {en:"Oil", tr:"Shemen", he:"שֶׁמֶן", pl:"Shmanim", plHe:"שְׁמָנִים",
  mn:"SHEH-men — same root as shamen, \"fat\". Shemen zayit = olive oil, the Hanukkah miracle oil.",
  ex:["Ani mevashelet im shemen zayit.","אֲנִי מְבַשֶּׁלֶת עִם שֶׁמֶן זַיִת.","I cook with olive oil."]}]},

{t:"Fruit", c:"Nouns · Food", w:[
 {en:"Grape", tr:"Anav", he:"עֲנָב", pl:"Anavim", plHe:"עֲנָבִים",
  mn:"a-NAV — grapes hang and NAB your eye. Usually plural: anavim.",
  ex:["Ha-anavim ha-eleh metukim me'od.","הָעֲנָבִים הָאֵלֶּה מְתוּקִים מְאוֹד.","These grapes are very sweet."]},
 {en:"Grapefruit", tr:"Eshkolit", he:"אֶשְׁכּוֹלִית", pl:"Eshkoliot", plHe:"אֶשְׁכּוֹלִיּוֹת",
  mn:"esh-ko-LEET — from eshkol, \"a cluster\" (grapefruits grow in clusters). Eshkol is also a famous Israeli surname.",
  ex:["Ani shotah mitz eshkoliot ba-boker.","אֲנִי שׁוֹתָה מִיץ אֶשְׁכּוֹלִיּוֹת בַּבֹּקֶר.","I drink grapefruit juice in the morning."]},
 {en:"Peach", tr:"Afarsek", he:"אֲפַרְסֵק", pl:"Afarsekim", plHe:"אֲפַרְסְקִים",
  mn:"a-far-SEK — from \"Persia\" (Persicum), just like the English \"peach\". Same fruit, same journey.",
  ex:["Ha-afarsek ha-ze ratuv ve-matok.","הָאֲפַרְסֵק הַזֶּה רָטוֹב וּמָתוֹק.","This peach is juicy and sweet."]},
 {en:"Pear", tr:"Agas", he:"אֲגָס", pl:"Agasim", plHe:"אֲגָסִים",
  mn:"a-GAS — a pear shaped like a little GAS balloon.",
  ex:["Kaniti agasim ba-shuk.","קָנִיתִי אֲגָסִים בַּשּׁוּק.","I bought pears at the market."]},
 {en:"Cherry", tr:"Duvdevan", he:"דּוּבְדְּבָן", pl:"Duvdevanim", plHe:"דּוּבְדְּבָנִים",
  mn:"duv-de-VAN — \"the cherry on top\" in Hebrew is ha-duvdevan she-ba-katzefet, \"the cherry on the whipped cream\". Say it three times; it's addictive.",
  ex:["Ha-duvdevan al ha-uga.","הַדֻּבְדְּבָן עַל הָעוּגָה.","The cherry is on the cake."]}]},

{t:"Sweet things", c:"Nouns · Food", w:[
 {en:"Blueberry", tr:"Uchmaniya", he:"אֻכְמָנִיָּה", pl:"Uchmaniyot", plHe:"אֻכְמָנִיּוֹת",
  mn:"uch-ma-nee-YA — from a root meaning \"dark/black\". Blueberries are the dark berries.",
  ex:["Ani ofa uga im uchmaniyot.","אֲנִי אוֹפָה עוּגָה עִם אֻכְמָנִיּוֹת.","I'm baking a cake with blueberries."]},
 {en:"Nut", tr:"Egoz", he:"אֱגוֹז", pl:"Egozim", plHe:"אֱגוֹזִים",
  mn:"eh-GOZ — the nut that GOES crack. Egoz melech = a walnut, literally \"king nut\".",
  ex:["Yesh egozim ba-salat.","יֵשׁ אֱגוֹזִים בַּסָּלָט.","There are nuts in the salad."]},
 {en:"Peanut", tr:"Boten", he:"בֹּטֶן", pl:"Botnim", plHe:"בֹּטְנִים",
  mn:"BO-ten — Israel's beloved snack Bamba is made of botnim. Say \"BOTTOM nut\".",
  ex:["Yesh li alergia le-botnim.","יֵשׁ לִי אָלֶרְגְּיָה לְבֹטְנִים.","I have an allergy to peanuts."]},
 {en:"Honey", tr:"Dvash", he:"דְּבַשׁ", pl:"—", plHe:"—",
  mn:"DVASH — \"a land flowing with milk and honey\" = eretz zavat chalav u-dvash. Sounds like a bee's buzz landing: \"dvash!\"",
  ex:["Ochlim tapuach be-dvash be-Rosh Hashana.","אוֹכְלִים תַּפּוּחַ בִּדְבַשׁ בְּרֹאשׁ הַשָּׁנָה.","We eat apple with honey on Rosh Hashanah."]},
 {en:"Jam / jelly", tr:"Riba", he:"רִבָּה", pl:"Ribot", plHe:"רִבּוֹת",
  mn:"REE-ba — a RIBBON of jam across your toast.",
  ex:["Ani mericha riba al ha-lechem.","אֲנִי מוֹרַחַת רִבָּה עַל הַלֶּחֶם.","I spread jam on the bread."]}]},

{t:"Meat and baking", c:"Nouns · Food", w:[
 {en:"Beef / cattle", tr:"Bakar", he:"בָּקָר", pl:"—", plHe:"—",
  mn:"ba-KAR — cattle you'd haul in a big CAR. Basar bakar = beef.",
  ex:["Ani lo ochel basar bakar.","אֲנִי לֹא אוֹכֵל בְּשַׂר בָּקָר.","I don't eat beef."]},
 {en:"Chicken / poultry (food)", tr:"Of", he:"עוֹף", pl:"Ofot", plHe:"עוֹפוֹת",
  mn:"OF — from la'uf, \"to fly\": poultry is \"the flying thing\". Different word from the live bird (tarnegol).",
  ex:["Ha-of ba-tanur kvar sha'a.","הָעוֹף בַּתַּנּוּר כְּבָר שָׁעָה.","The chicken has been in the oven for an hour."]},
 {en:"Pig / pork", tr:"Chazir", he:"חֲזִיר", pl:"Chazirim", plHe:"חֲזִירִים",
  mn:"cha-ZEER — sounds like a snorting \"cha-ZEEEER\". Slang: calling someone a chazir means they're a slob.",
  ex:["Hem lo ochlim basar chazir.","הֵם לֹא אוֹכְלִים בְּשַׂר חֲזִיר.","They don't eat pork."]},
 {en:"Butter", tr:"Chem'a", he:"חֶמְאָה", pl:"—", plHe:"—",
  mn:"chem-A — from cham (warm)? No — but it helps: butter melts when it's cham. Chem'at botnim = peanut butter.",
  ex:["Sim chem'a al ha-lechem ha-cham.","שִׂים חֶמְאָה עַל הַלֶּחֶם הַחַם.","Put butter on the warm bread."]},
 {en:"Flour", tr:"Kemach", he:"קֶמַח", pl:"—", plHe:"—",
  mn:"KEH-mach — \"Im ein kemach, ein Torah\" — \"without flour there's no Torah\", an old saying about needing bread before books.",
  ex:["Tzarich kemach la-uga.","צָרִיךְ קֶמַח לָעוּגָה.","We need flour for the cake."]}]},

{t:"Meals and dishes", c:"Nouns · Food", w:[
 {en:"Meal", tr:"Arucha", he:"אֲרוּחָה", pl:"Aruchot", plHe:"אֲרוּחוֹת",
  mn:"a-ROO-cha — arucha sounds like \"a ROUTINE\" — the routine three a day. Arucḥat boker = breakfast.",
  ex:["Aruchat erev be-shmoneh.","אֲרוּחַת עֶרֶב בִּשְׁמוֹנֶה.","Dinner is at eight."]},
 {en:"Dessert", tr:"Kinuach", he:"קִנּוּחַ", pl:"—", plHe:"—",
  mn:"kee-NOO-ach — from lekanach, \"to wipe clean\": dessert is what wipes the meal clean at the end.",
  ex:["Ma yesh le-kinuach?","מָה יֵשׁ לְקִנּוּחַ?","What's for dessert?"]},
 {en:"Sweetener / something sweet", tr:"Mamtik / Mamtika", he:"מַמְתִּיק / מַמְתִּיקָה", pl:"Mamtikim / Mamtikot", plHe:"מַמְתִּיקִים / מַמְתִּיקוֹת",
  mn:"mam-TEEK — from matok (sweet). The ma- prefix means \"the thing that makes it so\": the sweetener.",
  ex:["Ani lo sam mamtik ba-kafe.","אֲנִי לֹא שָׂם מַמְתִּיק בַּקָּפֶה.","I don't put sweetener in my coffee."]},
 {en:"Sauce / gravy", tr:"Rotev", he:"רוֹטֶב", pl:"Rotavim", plHe:"רְטָבִים",
  mn:"RO-tev — from ratuv, \"wet\". Sauce is the wet stuff.",
  ex:["Ha-rotev charif mid'i bishvili.","הָרוֹטֶב חָרִיף מִדַּי בִּשְׁבִילִי.","The sauce is too spicy for me."]},
 {en:"Piece", tr:"Chatichа", he:"חֲתִיכָה", pl:"Chatichot", plHe:"חֲתִיכוֹת",
  mn:"cha-tee-CHA — from lachtoch, \"to cut\": a piece is a cut-off bit. Slang warning: calling a person a chatich(a) means \"hottie\".",
  ex:["Ani rotza od chatichat uga.","אֲנִי רוֹצָה עוֹד חֲתִיכַת עוּגָה.","I want another piece of cake."]}]},

{t:"Ordering and cooking", c:"Nouns · Food", w:[
 {en:"Beverage / drink", tr:"Mashke", he:"מַשְׁקֶה", pl:"Mashkaot", plHe:"מַשְׁקָאוֹת",
  mn:"mash-KEH — from lehashkot, \"to give drink\". Related to the mashkeh (cupbearer) in the Joseph story.",
  ex:["Ma ata rotze lishtot? Yesh mashkaot karim.","מָה אַתָּה רוֹצֶה לִשְׁתּוֹת? יֵשׁ מַשְׁקָאוֹת קָרִים.","What do you want to drink? There are cold drinks."]},
 {en:"Alcoholic beverage", tr:"Mashke charif", he:"מַשְׁקֶה חָרִיף", pl:"Mashkaot charifim", plHe:"מַשְׁקָאוֹת חֲרִיפִים",
  mn:"charif means \"sharp/spicy\" — so alcohol is literally \"a sharp drink\". Same word you'd use for spicy food.",
  ex:["Hu lo shote mashkaot charifim.","הוּא לֹא שׁוֹתֶה מַשְׁקָאוֹת חֲרִיפִים.","He doesn't drink alcoholic beverages."]},
 {en:"Juice", tr:"Mitz", he:"מִיץ", pl:"—", plHe:"—",
  mn:"MEETS — juice that MEETS your thirst. Short and easy.",
  ex:["Mitz tapuzim tari, bevakasha.","מִיץ תַּפּוּזִים טָרִי, בְּבַקָּשָׁה.","Fresh orange juice, please."]},
 {en:"Menu", tr:"Tafrit", he:"תַּפְרִיט", pl:"Tafritim", plHe:"תַּפְרִיטִים",
  mn:"taf-REET — from prat, \"a detail\": a menu is the itemized list of details.",
  ex:["Ha-meltzar noten lanu tafrit.","הַמֶּלְצַר נוֹתֵן לָנוּ תַּפְרִיט.","The waiter gives us a menu."]},
 {en:"Recipe", tr:"Matkon", he:"מַתְכּוֹן", pl:"Matkonim", plHe:"מַתְכּוֹנִים",
  mn:"mat-KON — from tochen, \"content\": a recipe is the \"contents plan\". Sounds like \"MAT-CON\" — matching the contents.",
  ex:["Ze matkon shel savta sheli.","זֶה מַתְכּוֹן שֶׁל סָבְתָא שֶׁלִּי.","This is my grandmother's recipe."]},
 {en:"Ingredient / commodity", tr:"Mitzrach", he:"מִצְרָךְ", pl:"Mitzrachim", plHe:"מִצְרָכִים",
  mn:"mits-RACH — from tzarich, \"needed\": an ingredient is literally \"a needed thing\". Mitzrachim = groceries.",
  ex:["Kaniti et kol ha-mitzrachim la-matkon.","קָנִיתִי אֶת כָּל הַמִּצְרָכִים לַמַּתְכּוֹן.","I bought all the ingredients for the recipe."]}]}
];
