/* ===== NOUNS, part D — places, school & paper, time, abstract ===== */
const NOUNS_D = [
{t:"Places on the map", c:"Nouns · Places", w:[
 {en:"Place", tr:"Makom", he:"מָקוֹם", pl:"Mekomot", plHe:"מְקוֹמוֹת",
  mn:"ma-KOM — from lakum (to rise/stand): a place is where something stands. Ha-Makom (\"The Place\") is even a name for God.",
  ex:["Ze makom nechmad la-arucha.","זֶה מָקוֹם נֶחְמָד לָאֲרוּחָה.","This is a nice place for a meal."]},
 {en:"City", tr:"Ir", he:"עִיר", pl:"Arim", plHe:"עָרִים",
  mn:"EER — you HEAR the city. Iriya = the city hall. Note the vowel change in the plural: ir → arim.",
  ex:["Tel Aviv ir gdola ve-ra'ashanit.","תֵּל אָבִיב עִיר גְּדוֹלָה וְרַעֲשָׁנִית.","Tel Aviv is a big and noisy city."]},
 {en:"Country / land", tr:"Eretz", he:"אֶרֶץ", pl:"Aratzot", plHe:"אֲרָצוֹת",
  mn:"EH-rets — Eretz Yisrael. Artzot ha-Brit (\"lands of the covenant\") = the United States.",
  ex:["Be-eize eretz at gara?","בְּאֵיזוֹ אֶרֶץ אַתְּ גָּרָה?","Which country do you live in?"]},
 {en:"Address", tr:"Ktovet", he:"כְּתֹבֶת", pl:"Ktovot", plHe:"כְּתֹבוֹת",
  mn:"kto-VET — from lichtov (to write): an address is \"the written thing\". Also means a tattoo or an inscription.",
  ex:["Ma ha-ktovet shel ha-misrad?","מָה הַכְּתֹבֶת שֶׁל הַמִּשְׂרָד?","What's the office's address?"]},
 {en:"Road / way / path", tr:"Derech", he:"דֶּרֶךְ", pl:"Drachim", plHe:"דְּרָכִים",
  mn:"DEH-rech — \"derech eretz\" means good manners, literally \"the way of the land\". Also used for \"via / by way of\".",
  ex:["Ha-derech la-yam aruka.","הַדֶּרֶךְ לַיָּם אֲרֻכָּה.","The road to the sea is long."]}]},

{t:"Places you go", c:"Nouns · Places", w:[
 {en:"Store / shop", tr:"Chanut", he:"חֲנוּת", pl:"Chanuyot", plHe:"חֲנוּיוֹת",
  mn:"cha-NOOT — a shop where you HAND OUT goods. Sounds like \"HA-noot\".",
  ex:["Ha-chanut sgura be-shabbat.","הַחֲנוּת סְגוּרָה בְּשַׁבָּת.","The store is closed on Saturday."]},
 {en:"Office", tr:"Misrad", he:"מִשְׂרָד", pl:"Misradim", plHe:"מִשְׂרָדִים",
  mn:"mis-RAD — the mi- place-prefix again + sherut (service). A misrad is also a government ministry.",
  ex:["Ani oved ba-misrad me-tesha ad chamesh.","אֲנִי עוֹבֵד בַּמִּשְׂרָד מִתֵּשַׁע עַד חָמֵשׁ.","I work in the office from nine to five."]},
 {en:"School", tr:"Beit sefer", he:"בֵּית סֵפֶר", pl:"Batei sefer", plHe:"בָּתֵּי סֵפֶר",
  mn:"Literally \"house of book\". Bayit becomes beit when glued to another noun — beit cholim (hospital, \"house of the sick\"), beit kafe (café).",
  ex:["Ha-yeladim holchim le-beit sefer ba-boker.","הַיְּלָדִים הוֹלְכִים לְבֵית סֵפֶר בַּבֹּקֶר.","The children go to school in the morning."]},
 {en:"Library", tr:"Sifria", he:"סִפְרִיָּה", pl:"Sifriyot", plHe:"סִפְרִיּוֹת",
  mn:"sif-ree-YA — from sefer (book) + the -iya ending Hebrew uses for shops and places: sifriya, pitzeriya, mispara (barber).",
  ex:["Ani machzira sfarim la-sifria.","אֲנִי מַחְזִירָה סְפָרִים לַסִּפְרִיָּה.","I'm returning books to the library."]},
 {en:"Hotel", tr:"Malon", he:"מָלוֹן", pl:"Melonot", plHe:"מְלוֹנוֹת",
  mn:"ma-LON — from lalun, \"to stay the night\". Careful: malon = hotel, melon = the fruit.",
  ex:["Hazmanti cheder ba-malon le-shalosh laylot.","הִזְמַנְתִּי חֶדֶר בַּמָּלוֹן לְשָׁלוֹשׁ לֵילוֹת.","I booked a room at the hotel for three nights."]}]},

{t:"Travel", c:"Nouns · Places", w:[
 {en:"Airport", tr:"Nemal te'ufa", he:"נְמַל תְּעוּפָה", pl:"Nimlei te'ufa", plHe:"נִמְלֵי תְּעוּפָה",
  mn:"namal = a port, te'ufa = flying. An airport is literally \"a port of flight\".",
  ex:["Anachnu magi'im le-nemal ha-te'ufa be-arba.","אֲנַחְנוּ מַגִּיעִים לִנְמַל הַתְּעוּפָה בְּאַרְבַּע.","We arrive at the airport at four."]},
 {en:"Station / stop", tr:"Tachana", he:"תַּחֲנָה", pl:"Tachanot", plHe:"תַּחֲנוֹת",
  mn:"ta-cha-NA — from lachanot, \"to encamp\": a station is where you camp for a moment. Tachana merkazit = central bus station.",
  ex:["Ha-tachana ha-ba'a hi sheli.","הַתַּחֲנָה הַבָּאָה הִיא שֶׁלִּי.","The next stop is mine."]},
 {en:"Passport", tr:"Darkon", he:"דַּרְכּוֹן", pl:"Darkonim", plHe:"דַּרְכּוֹנִים",
  mn:"dar-KON — from derech (road/way): a passport is your \"road document\".",
  ex:["Al tishkach et ha-darkon ba-bayit!","אַל תִּשְׁכַּח אֶת הַדַּרְכּוֹן בַּבַּיִת!","Don't forget your passport at home!"]},
 {en:"Trip / hike", tr:"Tiyul", he:"טִיּוּל", pl:"Tiyulim", plHe:"טִיּוּלִים",
  mn:"tee-YOOL — Israelis are obsessed with the tiyul. It covers everything from a stroll to a six-month backpacking trek.",
  ex:["Anachnu osim tiyul ba-tzafon.","אֲנַחְנוּ עוֹשִׂים טִיּוּל בַּצָּפוֹן.","We're taking a trip in the north."]},
 {en:"Traffic / movement", tr:"Tnu'a", he:"תְּנוּעָה", pl:"—", plHe:"—",
  mn:"tnu-A — from lanua, \"to move\". Also means a political or youth movement, and a Hebrew vowel.",
  ex:["Yesh harbeh tnu'a ba-boker.","יֵשׁ הַרְבֵּה תְּנוּעָה בַּבֹּקֶר.","There's a lot of traffic in the morning."]}]},

{t:"In and out", c:"Nouns · Places", w:[
 {en:"Entrance", tr:"Knisa", he:"כְּנִיסָה", pl:"Knisot", plHe:"כְּנִיסוֹת",
  mn:"knee-SA — from lehikanes, \"to enter\". You'll see כניסה on every doorway in Israel.",
  ex:["Ha-knisa la-muzeon chinam.","הַכְּנִיסָה לַמּוּזֵאוֹן חִנָּם.","Entrance to the museum is free."]},
 {en:"Exit", tr:"Yetzia", he:"יְצִיאָה", pl:"Yetziot", plHe:"יְצִיאוֹת",
  mn:"yetz-ee-A — from latzet (to go out). Yetziat Mitzrayim = the Exodus from Egypt. Learn it as the pair to knisa.",
  ex:["Eifo ha-yetzia ha-krova?","אֵיפֹה הַיְּצִיאָה הַקְּרוֹבָה?","Where's the nearest exit?"]},
 {en:"Lake", tr:"Agam", he:"אֲגַם", pl:"Agamim", plHe:"אֲגַמִּים",
  mn:"a-GAM — a lake you'd want to go swimming in AGAIN.",
  ex:["Ha-agam shaket ba-boker.","הָאֲגַם שָׁקֵט בַּבֹּקֶר.","The lake is quiet in the morning."]},
 {en:"Truck / van", tr:"Masa'it", he:"מַשָּׂאִית", pl:"Masa'iot", plHe:"מַשָּׂאִיּוֹת",
  mn:"ma-sa-EET — from masa, \"a load\". A truck is \"the load-carrier\".",
  ex:["Ha-masa'it chosemet et ha-derech.","הַמַּשָּׂאִית חוֹסֶמֶת אֶת הַדֶּרֶךְ.","The truck is blocking the road."]},
 {en:"Service / bathroom (pl.)", tr:"Sherut", he:"שֵׁרוּת", pl:"Sherutim", plHe:"שֵׁרוּתִים",
  mn:"she-ROOT — from lesharet, to serve. Useful trap: in the plural, sherutim means \"the toilets\". A sherut is also a shared taxi.",
  ex:["Eifo ha-sherutim, bevakasha?","אֵיפֹה הַשֵּׁרוּתִים, בְּבַקָּשָׁה?","Where's the bathroom, please?"]},
 {en:"Weekend", tr:"Sof shavua", he:"סוֹף שָׁבוּעַ", pl:"—", plHe:"—",
  mn:"sof = end, shavua = week. \"End of week\" — and in Israel that's Friday–Saturday, not Saturday–Sunday.",
  ex:["Ma at osa be-sof shavua?","מָה אַתְּ עוֹשָׂה בְּסוֹף שָׁבוּעַ?","What are you doing this weekend?"]}]},

{t:"Books and stories", c:"Nouns · Words & paper", w:[
 {en:"Book", tr:"Sefer", he:"סֵפֶר", pl:"Sfarim", plHe:"סְפָרִים",
  mn:"SEH-fer — the Sefer Torah. Also sofer (writer), sifriya (library), sipur (story) — one big family.",
  ex:["Ha-sefer ha-ze me'anyen me'od.","הַסֵּפֶר הַזֶּה מְעַנְיֵן מְאוֹד.","This book is very interesting."]},
 {en:"Story", tr:"Sipur", he:"סִפּוּר", pl:"Sipurim", plHe:"סִפּוּרִים",
  mn:"see-POOR — from lesaper (to tell). \"Ze sipur acher\" = \"that's another story.\"",
  ex:["Saba mesaper sipur lifnei ha-sheina.","סָבָּא מְסַפֵּר סִפּוּר לִפְנֵי הַשֵּׁנָה.","Grandpa tells a story before bed."]},
 {en:"Word", tr:"Mila", he:"מִלָּה", pl:"Milim", plHe:"מִלִּים",
  mn:"mee-LA — a MILLION words to learn. (Mila also means circumcision — brit mila — from a different root.)",
  ex:["Ani lomedet chamesh milim chadashot kol yom.","אֲנִי לוֹמֶדֶת חָמֵשׁ מִלִּים חֲדָשׁוֹת כָּל יוֹם.","I learn five new words every day."]},
 {en:"Page / pillar", tr:"Amud", he:"עַמּוּד", pl:"Amudim", plHe:"עַמּוּדִים",
  mn:"a-MOOD — from la'amod (to stand): a pillar stands, and a page \"stands\" in a book. Same word for both.",
  ex:["Tiftechu et ha-sefer be-amud esrim.","תִּפְתְּחוּ אֶת הַסֵּפֶר בְּעַמּוּד עֶשְׂרִים.","Open the book to page twenty."]},
 {en:"Lesson / class", tr:"Shiur", he:"שִׁיעוּר", pl:"Shiurim", plHe:"שִׁיעוּרִים",
  mn:"shee-OOR — a shiur is a Torah class, and also a school lesson. Shiurei bayit = homework.",
  ex:["Yesh li shiur ivrit be-arba.","יֵשׁ לִי שִׁיעוּר עִבְרִית בְּאַרְבַּע.","I have a Hebrew lesson at four."]}]},

{t:"Writing tools", c:"Nouns · Words & paper", w:[
 {en:"Pen", tr:"Et", he:"עֵט", pl:"Etim", plHe:"עֵטִים",
  mn:"ET — two letters, like a pen stroke. Careful with the sound-alike et (אֶת), the object marker you use in every sentence.",
  ex:["Yesh lecha et? Ani rotza lichtov mashehu.","יֵשׁ לְךָ עֵט? אֲנִי רוֹצָה לִכְתֹּב מַשֶּׁהוּ.","Do you have a pen? I want to write something."]},
 {en:"Pencil", tr:"Iparon", he:"עִפָּרוֹן", pl:"Efronot", plHe:"עֶפְרוֹנוֹת",
  mn:"ee-pa-RON — from afar, \"dust/graphite\". A pencil is the dusty writer.",
  ex:["Ha-iparon shavur, tzarich lechadhed oto.","הָעִפָּרוֹן שָׁבוּר, צָרִיךְ לְחַדֵּד אוֹתוֹ.","The pencil is broken, it needs sharpening."]},
 {en:"Notebook", tr:"Machberet", he:"מַחְבֶּרֶת", pl:"Machbarot", plHe:"מַחְבָּרוֹת",
  mn:"mach-BEH-ret — from lechaber, \"to join/compose\": a notebook is bound pages joined together. Chaver (friend) is the same root — one who is joined to you.",
  ex:["Ani kotevet et ha-milim ba-machberet.","אֲנִי כּוֹתֶבֶת אֶת הַמִּלִּים בַּמַּחְבֶּרֶת.","I write the words in the notebook."]},
 {en:"Chalk", tr:"Gir", he:"גִּיר", pl:"Girim", plHe:"גִּירִים",
  mn:"GEER — chalk that makes you go \"GRR\" when it squeaks.",
  ex:["Ha-mora kotevet be-gir al ha-luach.","הַמּוֹרָה כּוֹתֶבֶת בְּגִיר עַל הַלּוּחַ.","The teacher writes with chalk on the board."]},
 {en:"Line", tr:"Kav", he:"קַו", pl:"Kavim", plHe:"קַוִּים",
  mn:"KAV — two letters, straight like a line. Also a bus route: kav 5 = the number 5 line.",
  ex:["Tzayer kav yashar ba-machberet.","צַיֵּר קַו יָשָׁר בַּמַּחְבֶּרֶת.","Draw a straight line in the notebook."]}]},

{t:"News and numbers", c:"Nouns · Words & paper", w:[
 {en:"Letter / message", tr:"Michtav", he:"מִכְתָּב", pl:"Michtavim", plHe:"מִכְתָּבִים",
  mn:"mich-TAV — from lichtov (to write). Note: this is a letter you MAIL. A letter of the alphabet is an ot.",
  ex:["Kibalti michtav me-ha-banak.","קִבַּלְתִּי מִכְתָּב מֵהַבַּנְק.","I got a letter from the bank."]},
 {en:"Newspaper", tr:"Iton", he:"עִתּוֹן", pl:"Itonim", plHe:"עִתּוֹנִים",
  mn:"ee-TON — from et, \"time\": a newspaper is \"the time-thing\", like the English \"Times\".",
  ex:["Aba kore iton kol boker.","אַבָּא קוֹרֵא עִתּוֹן כָּל בֹּקֶר.","Dad reads a newspaper every morning."]},
 {en:"News", tr:"— (plural only)", he:"—", pl:"Chadashot", plHe:"חֲדָשׁוֹת",
  mn:"cha-da-SHOT — literally \"new things\", the plural of chadash (new). Only ever used in the plural.",
  ex:["Ha-chadashot mat-chilot be-shmoneh.","הַחֲדָשׁוֹת מַתְחִילוֹת בִּשְׁמוֹנֶה.","The news starts at eight."]},
 {en:"Number", tr:"Mispar", he:"מִסְפָּר", pl:"Misparim", plHe:"מִסְפָּרִים",
  mn:"mis-PAR — from lispor, \"to count\". Sounds like \"miss PAR\" — off by a number.",
  ex:["Ma mispar ha-telefon shelcha?","מָה מִסְפַּר הַטֶּלֶפוֹן שֶׁלְּךָ?","What's your phone number?"]},
 {en:"Answer / reply", tr:"Tshuva", he:"תְּשׁוּבָה", pl:"Tshuvot", plHe:"תְּשׁוּבוֹת",
  mn:"tshoo-VA — from lashuv, \"to return\": an answer is what comes back. Also \"repentance\" — a return to the right path.",
  ex:["Ein li tshuva la-she'ela ha-zo.","אֵין לִי תְּשׁוּבָה לַשְּׁאֵלָה הַזֹּאת.","I don't have an answer to this question."]}]},

{t:"Pictures and examples", c:"Nouns · Words & paper", w:[
 {en:"Picture / photo", tr:"Tmuna", he:"תְּמוּנָה", pl:"Tmunot", plHe:"תְּמוּנוֹת",
  mn:"tmoo-NA — think of a picture you MOUNT on the wall: t-MOUNT-a.",
  ex:["Yesh tmunot yafot al ha-kir.","יֵשׁ תְּמוּנוֹת יָפוֹת עַל הַקִּיר.","There are beautiful pictures on the wall."]},
 {en:"Drawing", tr:"Tziur", he:"צִיּוּר", pl:"Tziurim", plHe:"צִיּוּרִים",
  mn:"tsee-YOOR — from letzayer, to draw, and tzayar, a painter. A tziur is what a tzayar makes.",
  ex:["Ha-tziur shel ha-yalda tzivoni.","הַצִּיּוּר שֶׁל הַיַּלְדָּה צִבְעוֹנִי.","The girl's drawing is colorful."]},
 {en:"Example", tr:"Dugma", he:"דֻּגְמָה", pl:"Dugmaot", plHe:"דֻּגְמָאוֹת",
  mn:"DOOG-ma — same root as dugman, a model. Lemashal / le-dugma = \"for example\".",
  ex:["Ten li dugma, bevakasha.","תֵּן לִי דֻּגְמָה, בְּבַקָּשָׁה.","Give me an example, please."]},
 {en:"Information", tr:"Meida", he:"מֵידָע", pl:"—", plHe:"—",
  mn:"may-DA — from lada'at, \"to know\": information is \"knowable stuff\". You'll see מידע on every info desk.",
  ex:["Ein li mespik meida al ha-tiyul.","אֵין לִי מַסְפִּיק מֵידָע עַל הַטִּיּוּל.","I don't have enough information about the trip."]},
 {en:"Booklet / pamphlet", tr:"Choveret", he:"חוֹבֶרֶת", pl:"Chovrot", plHe:"חוֹבְרוֹת",
  mn:"cho-VEH-ret — from lechaber (to join), just like machberet. A choveret is a thin stapled booklet.",
  ex:["Kibalti choveret im kol ha-prati'im.","קִבַּלְתִּי חוֹבֶרֶת עִם כָּל הַפְּרָטִים.","I got a booklet with all the details."]},
 {en:"Workbook", tr:"Choveret avoda", he:"חוֹבֶרֶת עֲבוֹדָה", pl:"Chovrot avoda", plHe:"חוֹבְרוֹת עֲבוֹדָה",
  mn:"Booklet + avoda (work). Hebrew stacks nouns to build compounds — you've now seen this a dozen times.",
  ex:["Ha-talmidim potchim et choveret ha-avoda.","הַתַּלְמִידִים פּוֹתְחִים אֶת חוֹבֶרֶת הָעֲבוֹדָה.","The students open the workbook."]}]},

{t:"Telling the time", c:"Nouns · Time", w:[
 {en:"Hour / o'clock", tr:"Sha'a", he:"שָׁעָה", pl:"Sha'ot", plHe:"שָׁעוֹת",
  mn:"sha-A — related to shaon (watch/clock). Ma ha-sha'a? = \"What time is it?\"",
  ex:["Chikiti sha'a shlema.","חִכִּיתִי שָׁעָה שְׁלֵמָה.","I waited a whole hour."]},
 {en:"Minute", tr:"Daka", he:"דַּקָּה", pl:"Dakot", plHe:"דַּקּוֹת",
  mn:"da-KA — from dak, \"thin/fine\": a minute is a fine slice of an hour. \"Rega, daka!\" = \"Wait, one minute!\"",
  ex:["Ani magi'a be-eser dakot.","אֲנִי מַגִּיעַ בְּעֶשֶׂר דַּקּוֹת.","I'll arrive in ten minutes."]},
 {en:"Second", tr:"Shniya", he:"שְׁנִיָּה", pl:"Shniyot", plHe:"שְׁנִיּוֹת",
  mn:"shnee-YA — from shtayim/sheni, \"two/second\". Just like English: the \"second\" division of an hour.",
  ex:["Rak shniya, ani ba!","רַק שְׁנִיָּה, אֲנִי בָּא!","Just a second, I'm coming!"]},
 {en:"Year", tr:"Shana", he:"שָׁנָה", pl:"Shanim", plHe:"שָׁנִים",
  mn:"sha-NA — Rosh Hashana = \"head of the year\". Shana tova = happy new year.",
  ex:["Ani gar po shalosh shanim.","אֲנִי גָּר פֹּה שָׁלוֹשׁ שָׁנִים.","I've lived here for three years."]},
 {en:"Month", tr:"Chodesh", he:"חֹדֶשׁ", pl:"Chodashim", plHe:"חֳדָשִׁים",
  mn:"CHO-desh — from chadash, \"new\": a month begins with the new moon. Watch the near-twins: chodesh (month) vs. chadash (new).",
  ex:["Ba-chodesh ha-ba anachnu nos'im le-chul.","בַּחֹדֶשׁ הַבָּא אֲנַחְנוּ נוֹסְעִים לְחוּ\"ל.","Next month we're traveling abroad."]}]},

{t:"Time and its parts", c:"Nouns · Time", w:[
 {en:"Beginning", tr:"Hatchala", he:"הַתְחָלָה", pl:"Hatchalot", plHe:"הַתְחָלוֹת",
  mn:"hat-cha-LA — from lehatchil (to begin). Bereshit, the first word of the Torah, means \"in the beginning\" — but hatchala is the everyday word.",
  ex:["Ze rak ha-hatchala.","זֶה רַק הַהַתְחָלָה.","This is only the beginning."]},
 {en:"Past", tr:"Avar", he:"עָבָר", pl:"—", plHe:"—",
  mn:"a-VAR — from la'avor, \"to pass\": the past is what has passed. It's also the name of the past tense — your Phase 2 material.",
  ex:["Ba-avar garti be-Yerushalayim.","בֶּעָבָר גַּרְתִּי בִּירוּשָׁלַיִם.","In the past I lived in Jerusalem."]},
 {en:"Break / pause / intermission", tr:"Hafsaka", he:"הַפְסָקָה", pl:"Hafsakot", plHe:"הַפְסָקוֹת",
  mn:"haf-sa-KA — from lehafsik, \"to stop\". School recess, a coffee break, and a theatre intermission are all a hafsaka.",
  ex:["Bo'i nikach hafsaka shel eser dakot.","בּוֹאִי נִקַּח הַפְסָקָה שֶׁל עֶשֶׂר דַּקּוֹת.","Let's take a ten-minute break."]},
 {en:"Board / calendar", tr:"Luach", he:"לוּחַ", pl:"Luchot", plHe:"לוּחוֹת",
  mn:"LOO-ach — the Ten Commandments were on luchot ha-brit, stone tablets. A luach shana is a yearly calendar, and a classroom blackboard is a luach too.",
  ex:["Ha-luach talui al ha-kir ba-mitbach.","הַלּוּחַ תָּלוּי עַל הַקִּיר בַּמִּטְבָּח.","The calendar hangs on the kitchen wall."]}]},

{t:"Ideas and truth", c:"Nouns · Abstract", w:[
 {en:"Idea", tr:"Ra'ayon", he:"רַעְיוֹן", pl:"Ra'ayonot", plHe:"רַעְיוֹנוֹת",
  mn:"ra-a-YON — an idea that goes ON and ON. \"Yesh li ra'ayon!\" = \"I have an idea!\"",
  ex:["Yesh li ra'ayon metzuyan.","יֵשׁ לִי רַעְיוֹן מְצֻיָּן.","I have an excellent idea."]},
 {en:"Reason / cause", tr:"Siba", he:"סִבָּה", pl:"Sibot", plHe:"סִבּוֹת",
  mn:"SEE-ba — a reason you can SEE. Mi-siba she… = \"for the reason that…\"",
  ex:["Ein siba lidog.","אֵין סִבָּה לִדְאֹג.","There's no reason to worry."]},
 {en:"Truth", tr:"Emet", he:"אֱמֶת", pl:"—", plHe:"—",
  mn:"eh-MET — say AMEN and you affirm the emet. Same root a-m-n as \"believe\".",
  ex:["Tagid li et ha-emet, bevakasha.","תַּגִּיד לִי אֶת הָאֱמֶת, בְּבַקָּשָׁה.","Tell me the truth, please."]},
 {en:"Mistake / error", tr:"Ta'ut", he:"טָעוּת", pl:"Ta'uyot", plHe:"טָעֻיּוֹת",
  mn:"ta-OOT — you went off route: \"ta-OUT of the way\". \"Ta'ut be-mispar\" = \"wrong number\" on the phone.",
  ex:["Asiti ta'ut ba-cheshbon.","עָשִׂיתִי טָעוּת בַּחֶשְׁבּוֹן.","I made a mistake in the calculation."]},
 {en:"Difference", tr:"Hevdel", he:"הֶבְדֵּל", pl:"Hevdelim", plHe:"הֶבְדֵּלִים",
  mn:"hev-DEL — from lehavdil, \"to separate\". Havdala is the Saturday-night ceremony separating Shabbat from the week.",
  ex:["Ma ha-hevdel ben ha-shnayim?","מָה הַהֶבְדֵּל בֵּין הַשְּׁנַיִם?","What's the difference between the two?"]}]},

{t:"Color and celebration", c:"Nouns · Abstract", w:[
 {en:"Confusion / chaos", tr:"Bilbul", he:"בִּלְבּוּל", pl:"Bilbulim", plHe:"בִּלְבּוּלִים",
  mn:"bil-BOOL — from the Tower of BABEL (Bavel), where all the languages got confused. The word even sounds jumbled.",
  ex:["Haya bilbul gadol ba-tachana.","הָיָה בִּלְבּוּל גָּדוֹל בַּתַּחֲנָה.","There was a big mix-up at the station."]},
 {en:"Color", tr:"Tzeva", he:"צֶבַע", pl:"Tzva'im", plHe:"צְבָעִים",
  mn:"TSEH-va — from litzbo'a (to paint). Eize tzeva ata ohev? = \"What color do you like?\"",
  ex:["Eize tzeva ha-simla shela?","אֵיזֶה צֶבַע הַשִּׂמְלָה שֶׁלָּהּ?","What color is her dress?"]},
 {en:"Flag", tr:"Degel", he:"דֶּגֶל", pl:"Degalim", plHe:"דְּגָלִים",
  mn:"DEH-gel — a flag with a DANGLE. Degel Yisrael = the Israeli flag.",
  ex:["Ha-degel mit-nofef ba-ruach.","הַדֶּגֶל מִתְנוֹפֵף בָּרוּחַ.","The flag waves in the wind."]},
 {en:"Gift / present", tr:"Matana", he:"מַתָּנָה", pl:"Matanot", plHe:"מַתָּנוֹת",
  mn:"ma-ta-NA — from latet (to give), root n-t-n. A gift is \"a given thing\".",
  ex:["Kibalti matana yafa me-ha-achot sheli.","קִבַּלְתִּי מַתָּנָה יָפָה מֵהָאָחוֹת שֶׁלִּי.","I got a lovely gift from my sister."]},
 {en:"Treasure", tr:"Otzar", he:"אוֹצָר", pl:"Otzarot", plHe:"אוֹצָרוֹת",
  mn:"o-TSAR — an OZ-like hoard. Sar ha-otzar = the finance minister, \"minister of the treasury\".",
  ex:["Ha-yeladim mechapsim otzar ba-chol.","הַיְּלָדִים מְחַפְּשִׂים אוֹצָר בַּחוֹל.","The children are looking for treasure in the sand."]}]},

{t:"Nature and objects", c:"Nouns · Abstract", w:[
 {en:"Flower", tr:"Perach", he:"פֶּרַח", pl:"Prachim", plHe:"פְּרָחִים",
  mn:"PEH-rach — from lifro'ach, \"to bloom\". Perach also means a cadet or trainee — someone still blooming.",
  ex:["Kaniti prachim la-shulchan.","קָנִיתִי פְּרָחִים לַשֻּׁלְחָן.","I bought flowers for the table."]},
 {en:"Leaf / page", tr:"Aleh", he:"עָלֶה", pl:"Alim", plHe:"עָלִים",
  mn:"a-LEH — from la'alot, \"to go up\": a leaf grows upward. Same word family as oleh (immigrant) and aliyah.",
  ex:["Ha-alim adumim ba-stav.","הֶעָלִים אֲדֻמִּים בַּסְּתָיו.","The leaves are red in autumn."]},
 {en:"Wave", tr:"Gal", he:"גַּל", pl:"Galim", plHe:"גַּלִּים",
  mn:"GAL — a wave that gives you a GALLON of water. Galgal (wheel) is gal doubled — something that rolls.",
  ex:["Ha-galim gvohim ha-yom ba-yam.","הַגַּלִּים גְּבוֹהִים הַיּוֹם בַּיָּם.","The waves are high at the sea today."]},
 {en:"Pouring rain / flood", tr:"Mabul", he:"מַבּוּל", pl:"—", plHe:"—",
  mn:"ma-BOOL — Noah's Flood is Ha-Mabul. Israelis use it for any downpour: \"Yesh mabul ba-chutz!\"",
  ex:["Yesh mabul ba-chutz, al tetze bli me'il.","יֵשׁ מַבּוּל בַּחוּץ, אַל תֵּצֵא בְּלִי מְעִיל.","It's pouring outside, don't go out without a coat."]},
 {en:"Ball", tr:"Kadur", he:"כַּדּוּר", pl:"Kadurim", plHe:"כַּדּוּרִים",
  mn:"ka-DOOR — kadur is also a pill and a bullet — anything small and round. Kadur ha-aretz = the globe; kaduregel = soccer.",
  ex:["Ha-yeladim mesachakim im kadur ba-gan.","הַיְּלָדִים מְשַׂחֲקִים עִם כַּדּוּר בַּגַּן.","The children play with a ball in the park."]},
 {en:"Piano", tr:"Psanter", he:"פְּסַנְתֵּר", pl:"Psanterim", plHe:"פְּסַנְתֵּרִים",
  mn:"psan-TER — from the Greek \"psalterion\", the same ancestor as \"psalm\" and \"psaltery\".",
  ex:["Yesh psanter yashan ba-salon.","יֵשׁ פְּסַנְתֵּר יָשָׁן בַּסָּלוֹן.","There's an old piano in the living room."]},
 {en:"Crab / cancer", tr:"Sartan", he:"סַרְטָן", pl:"Sartanim", plHe:"סַרְטָנִים",
  mn:"sar-TAN — like English, the animal and the disease share a name (Latin \"cancer\" = crab). Also the zodiac sign Cancer.",
  ex:["Ra'inu sartan katan al ha-chof.","רָאִינוּ סַרְטָן קָטָן עַל הַחוֹף.","We saw a small crab on the beach."]}]}
];
